### ISSUE TITLE
Vertical "middle" or "center"?

### ISSUE THREAD

**Issue by stnever** [guyonroche/exceljs#10]
Hi! I have an .xlsx file, created in Excel, with a vertically-centered cell. Its alignment value seems to be "center" instead of "middle":

    in xl/styles.xml:
    ...
    <alignment horizontal="left" vertical="center" textRotation="0" 
      wrapText="false" indent="0" shrinkToFit="false"/>
   ...

Unfortunately I don't have Excel on my computer right now, only LibreOffice, but it seems to honor the "center" value and renders correctly (vertically centered).

But when I generate an .xlsx using exceljs, if I use `alignment = {vertical: 'center'}`, it is not written to the output file (because `center` is not a legal value for alignment in the current API). And if I use `middle`, it DOES get written to the output file but LibreOffice doesn't honor it and displays the text in the bottom of the cell.

I quickly hacked alignment.js:158 to look like this:

    validVertical: function(value) {
      if ( value == "middle" ) return "center"; // added this line
      return this.validVerticalValues[value] ? value : undefined;
    },

Now, I can use the "middle" value as the API expects, but it outputs "center" in the final file, and things work (on LibreOffice, that is; I still have to check on Excel).

I'm not sure, maybe this is just LibreOffice's fault, and the "middle" value is correct? I'm still searching for some documentation on the format.

**Comment by guyonroche** [comment]
Thanks for this! My bad... Excel also uses "center" for vertical alignment. I assumed it would follow the UI labels.
Will include this fix in the next publish.

**Comment by guyonroche** [comment]
Published in exceljs@0.1.11.
"middle" is translated to "center" during XLSX writes and back to "middle" again during read.
