### ISSUE TITLE
have a problem while using exceljs

### ISSUE THREAD

**Issue by dingquantracy** [guyonroche/exceljs#11]
[Error: Cannot find module './xlsx/.rels'] code: 'MODULE_NOT_FOUND' .  It is ok when running offline, but it reports the error when put it on line.  I cant figure it out.  help~~~

**Comment by guyonroche** [comment]
This file is a template file used by the xlsx writer to build the xlsx file. You should be able to find it at [your-project-root]/node_modules/exceljs/lib/xlsx/.rels

**Comment by guyonroche** [comment]
@dingquantracy - have you resolved this? I'd like to close this issue if it is.

**Comment by guyonroche** [comment]
Closing now as I'm going to assume it is resolved. Please reopen if still an issue.

**Comment by Thomsos** [comment]
Hey, I am now having this issue. I tried finding it in the directory you specified, but it was not there. Any help?

**Comment by danieleds** [comment]
In my case, it was because the build system was not copying dot files (`.*`)
