### ISSUE TITLE
Clientside JS?

### ISSUE THREAD

**Issue by lacivert** [guyonroche/exceljs#12]
Is there a chance to use this on clientside js? For example click a button and get the excel document from the data on the browser like downloading a document?

**Comment by guyonroche** [comment]
I'll have to look into it.

**Comment by ismailbaskin** [comment]
this can be usefull https://stuk.github.io/jszip/

**Comment by perymimon** [comment]
I join to Lacivert request. 
can browserify can handle that?

**Comment by TheBrianJ** [comment]
Any progress?

**Comment by guyonroche** [comment]
Finally - yes, this is fixed in 0.2.42 :-D

**Comment by ismailbaskin** [comment]
@lacivert hadi hayırlı olsun

**Comment by wei-nete** [comment]
How to use exceljs to achieve this, can anyone provide an example?

**Comment by guyonroche** [comment]
@wei-nete you can take a look at the [spec/browser](https://github.com/guyonroche/exceljs/tree/master/spec/browser) folder in the github repo which demos a web page creating a spreadsheet, sending it to the server and receiving a modified version.
