### ISSUE TITLE
Adding an option to set RTL worksheet

### ISSUE THREAD

**Issue by dorshay6** [guyonroche/exceljs#126]
Header

**Comment by deanshub** [comment]
my excel installation is RTL by default so this code makes it LTR I guess you can use it to make the opposite work
```
const worksheet = workbook.getWorksheet(1);
worksheet.views = [{state:'normal'}];
```
I found it by saving an excel file as I want then I read it and viewed it's properties, something like that:
```
workbook.xlsx.readFile('test.xlsx')
    .then(function() {
      const worksheet = workbook.getWorksheet(1);
      console.log(worksheet.views);
    });
```
