### ISSUE TITLE
getRows function?

### ISSUE THREAD

**Issue by VanDalkvist** [guyonroche/exceljs#13]
Do you want to implement something like getRows function? I know about ```_rows``` object, but I don't know it is stable or not.

**Comment by guyonroche** [comment]
Yes - accessing _rows is not advised. I prefix with _ to indicate "private" implementation members and cannot guarantee their stability.
What is the the desired result of this getRows function? the _rows member contains a sparse array of Row objects - if what you're after is an array of array of cell values, then getSheetValues would be a better name.
Let me know

**Comment by VanDalkvist** [comment]
@guyonroche I understand. I think it will be more easy to get all rows by getRows function. In my case it does not matter how it will return. An array of array of cell values will be good and as array of Row objects also. I parse CSV file and I need fetch all rows and return it as values.

By the way, Will you implement support in parsing CSV files optional settings to parse first row of a file as a 'Columns' row? And add it to worksheet as columns.

**Comment by guyonroche** [comment]
If all you want to do is iterate over the rows and values, you can use:
 + worksheet.eachRow(function(row, rowNumber) { ... });
 + row.eachCell(function(cell, colNumber) { ... });

Regarding parsing CSV, I haven't made any distinction about the first row yet - it will be added to the sheet as data like the other rows. I can see a few possible options though - I'll add it to the backlog

**Comment by VanDalkvist** [comment]
Yes, I have already done it by this way. Thank you
