### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by mn1aC** [guyonroche/exceljs#14]
How to get the dimensions (e.g. number of rows) from a file?

**Comment by guyonroche** [comment]
// For each sheet in the workbook, you can access the id, name and dimensions.
// the dimensions object supports, left, top, bottom, right, as numbers and tl, br and range strings
var workbook = new Workbook();
workbook.xlsx.readFile(filename)
    .then(function() {
        workbook.eachSheet(function(worksheet) {
            console.log("Sheet " + worksheet.id + 
                 " - " + worksheet.name + 
                 ", Dims=" + worksheet.dimensions);
        });
    })
    .catch(function(error) {
        console.log(error.message);
    });
