### ISSUE TITLE
Line break in one cell

### ISSUE THREAD

**Issue by kitlee** [guyonroche/exceljs#143]
I want to display an array of string in a cell, but I get an error stating "I do not understand the type..." or something like that.

For now, I display the array with `array.join(',')`, I did try `array.join('\n')` and `array.join('\r\n')`, but no luck.

Are there any workaround for this problem?

**Comment by CrashedBboy** [comment]
Hi, have you found the solution?  
I'm getting into the same trouble as well

**Comment by kitlee** [comment]
Not sure which version I was using, I am using 0.2.33 now
It works with `array.join('\r\n')`

**Comment by pyatskevich** [comment]
Line break don't work in ver. 0.3.0, I used 0.2.33 to make it working.
