### ISSUE TITLE
Support for .xls

### ISSUE THREAD

**Issue by nicktunac** [guyonroche/exceljs#148]
Some of my files are using lower version of excel.

**Comment by antunezz** [comment]
So, doesn't this library work with .xls files??

**Comment by tjsail33** [comment]
No. `.xls` is a proprietary format owned by Microsoft. `.xlsx` is an open XML based format.

**Comment by brauliobo** [comment]
the Excel 2003 is an open xml format: https://learn.microsoft.com/en-us/previous-versions/office/developer/office-xp/aa140066(v=office.10)
