### ISSUE TITLE
Fill pattern solid turns all color into black

### ISSUE THREAD

**Issue by haoliangyu** [guyonroche/exceljs#149]
I am using the following code to set background color of cells

``` javascript
row.getCell(column).fill = {
  type: 'pattern',
  pattern: 'solid',
  bgColor: { argb: 'whatever-color' }
};
```

No matter what color I input, I still get a black cell. If I change the pattern to the other, I can see the actual color. Is that a default behaviour of `solid` pattern, or just a bug?

**Comment by Zacharis278** [comment]
Running into the same issue.  @haoliangyu did you find a solution?

**Comment by haoliangyu** [comment]
If you set the `pattern` as `solid`, it will only render `fgColor`, not `bgColor`. See [detail explanation at the bottom](http://webapp.docx4java.org/OnlineDemo/ecma376/SpreadsheetML/ST_PatternType.html)

**Comment by KevinWang15** [comment]
So.. in order to set the background of the cell to `#EEEEEE`, I will have to use

```javascript
cell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: {argb: 'EEEEEE'}
};
```

I totally misunderstood what `fgColor` and `bgColor` meant in `fill`.

Here is a good explanation: https://stackoverflow.com/a/43741294/6247478

> Note that the background color of your cell will be the foreground color (fgColor) of the fill property. It sounds confusing, but it makes sense when you understand that the fill property have patterns that use more than one color, hence the property having foreground and background colors.
> 
> The 'solid' patternType is probably what you're looking for, but there are others, such as 'darkDown', 'darkHorizontal', 'lightGrid', and etc, as can be seen here: [excel4node/fillPattern.js](https://github.com/amekkawi/excel4node/blob/master/source/lib/types/fillPattern.js)
