### ISSUE TITLE
Function "eachCell" does not work as expected

### ISSUE THREAD

**Issue by VanDalkvist** [guyonroche/exceljs#15]
When I try use ```eachCell``` function it works strange. It seems that it dismiss null/undefined value or something like that.
```
// ...
var parsedRow = {};
row.eachCell(function (cell, col) {
       parsedRow[columnsRow.getCell(col).value] = cell.value;
});

```
For example, if I have 30 columns and some of them equals ""(empty string in the file) then ``` Object.keys(parsedRow).length ``` expression can return 26.

**Comment by VanDalkvist** [comment]
I just saw your sources files and see next: 
```
eachRow: function(iteratee) {
        this._rows.forEach(function(row) {
            if (row.hasValues) {
                iteratee(row, row.number);
            }
        });
    },
```
For me, it is not expected behaviour, because if we have strong order of properties it will be wrong in the output. 
Instead of your function ```eachRow``` I have to use this construction: 
```
var parsedRow = {};
// here counting starts from 1
for (var col = 1; col < row.values.length; col++) {
      var cell = row.getCell(col);
      parsedRow[columnsRow.getCell(col).value] = cell.value;
}
```

**Comment by guyonroche** [comment]
I guess the "each" functions could take an optional boolean argument like "includeEmpty" that would behave more like you want. I'll add it to the next release.

**Comment by guyonroche** [comment]
The <a href="https://www.npmjs.com/package/exceljs#rows">eachRow and eachCell</a> functions now support an optional options argument that will git you the behaviour you need...

```javascript
worksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) {
    row.eachCell{ includeEmpty: true }, function(cell, colNumber) {
        console.log("Cell " + colNumber + " on Row " + rowNumber + " = " + cell.value);
    });
});
```

**Comment by VanDalkvist** [comment]
Great, Thank you!
