### ISSUE TITLE
[Regression] Stream API fails to write XLSX files

### ISSUE THREAD

**Issue by danieleds** [guyonroche/exceljs#150]
Since version 0.2.10, exceljs fails to write xlsx files using the stream API with the following error:

```
Unhandled rejection Error: append: input source must be valid Stream or Buffer instance
    at Archiver.append (/home/bugreport/backend/node_modules/archiver/lib/core.js:333:24)
    at /home/bugreport/backend/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:251:18
    at Promise._execute (/home/bugreport/backend/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.WorkbookWriter.addSharedStrings (/home/bugreport/backend/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:250:14)
    at /home/bugreport/backend/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:131:16
    at tryCatcher (/home/bugreport/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:447:14)
    at Promise._settlePromiseFromHandler (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:561:18)
```

This is the code to reproduce the problem:

```js
const fs = require('fs');
const Excel = require('exceljs');

let outStream = fs.createWriteStream('/tmp/aaa', {flags: 'w'})

let options = {
    stream: outStream,
    useStyles: true,
    useSharedStrings: true
};

let workbook = new Excel.stream.xlsx.WorkbookWriter(options);
let worksheet = workbook.addWorksheet('test');
let newrow = worksheet.addRow(['hello']);
newrow.commit();
worksheet.commit();
workbook.commit();
```

If you do not add any row, it works fine.
Also, worked fine on 0.2.9 and previous versions.

**Comment by lgaticaq** [comment]
Some error. My code

```js
router.get("/", (req, res, next) => {  
  const options = {
    stream: res,
    useStyles: true,
    useSharedStrings: true
  }
  const workbook = new Excel.stream.xlsx.WorkbookWriter(options)
  const sheet = workbook.addWorksheet("Report")
  const worksheet = workbook.getWorksheet("Report")
  worksheet.columns = [
    {width: 20},
    {width: 12},
    {width: 30},
    {width: 18},
    {width: 30},
    {width: 6}
  ]
  const box = {
    top: {style: "thin"},
    left: {style: "thin"},
    bottom: {style: "thin"},
    right: {style: "thin"}
  }
  const bold = {name: "Calibri", bold: true}
  const center = {vertical: "bottom", horizontal: "center"}
  worksheet.mergeCells("A7:B7")
  worksheet.getCell("A7").alignment = center
  worksheet.getCell("A7").border = box
  worksheet.getCell("A7").font = bold
  worksheet.getCell("A7").value = "DETAILS"
  worksheet.mergeCells("A10:F10")
  worksheet.getCell("A10").alignment = center
  worksheet.getCell("A10").border = box
  worksheet.getCell("A10").font = bold
  worksheet.getRow(11).commit()
  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
  res.setHeader("Content-disposition", `attachment;filename=Reporte ${date}.xlsx`)
  workbook.commit()
})
```

**Comment by ddddm** [comment]
Also getting this error

**Comment by danieleds** [comment]
This issue is still present with exceljs@0.2.15 and the latest version of Node.js.

**Comment by danieleds** [comment]
I think I have fixed it thanks to this simple patch: https://github.com/danieleds/exceljs/commit/d5011ba46c5192942d1aa7aa6790a2a0459b54e3

I've opened a pull request at #175

**Comment by guyonroche** [comment]
I'll look at this shortly

**Comment by guyonroche** [comment]
Merged the PR. I also added an integration-test that used your example @danieleds so this regression should not happen again.
Thanks everyone!

**Comment by danieleds** [comment]
Thank you for the wonderful project!

**Comment by majid-rafei** [comment]
> Since version 0.2.10, exceljs fails to write xlsx files using the stream API with the following error:
> 
> ```
> Unhandled rejection Error: append: input source must be valid Stream or Buffer instance
>     at Archiver.append (/home/bugreport/backend/node_modules/archiver/lib/core.js:333:24)
>     at /home/bugreport/backend/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:251:18
>     at Promise._execute (/home/bugreport/backend/node_modules/bluebird/js/release/debuggability.js:272:9)
>     at Promise._resolveFromExecutor (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:475:18)
>     at new Promise (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:77:14)
>     at Object.WorkbookWriter.addSharedStrings (/home/bugreport/backend/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:250:14)
>     at /home/bugreport/backend/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:131:16
>     at tryCatcher (/home/bugreport/backend/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:504:31)
>     at Promise._settlePromise (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:561:18)
>     at Promise._settlePromise0 (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:606:10)
>     at Promise._settlePromises (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:685:18)
>     at Promise._fulfill (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:630:18)
>     at Promise._resolveCallback (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:447:14)
>     at Promise._settlePromiseFromHandler (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:516:17)
>     at Promise._settlePromise (/home/bugreport/backend/node_modules/bluebird/js/release/promise.js:561:18)
> ```
> 
> This is the code to reproduce the problem:
> 
> ```js
> const fs = require('fs');
> const Excel = require('exceljs');
> 
> let outStream = fs.createWriteStream('/tmp/aaa', {flags: 'w'})
> 
> let options = {
>     stream: outStream,
>     useStyles: true,
>     useSharedStrings: true
> };
> 
> let workbook = new Excel.stream.xlsx.WorkbookWriter(options);
> let worksheet = workbook.addWorksheet('test');
> let newrow = worksheet.addRow(['hello']);
> newrow.commit();
> worksheet.commit();
> workbook.commit();
> ```
> 
> If you do not add any row, it works fine. Also, worked fine on 0.2.9 and previous versions.

I have the same error.
