### ISSUE TITLE
Is it possible to set number of decimal places for a numeric cell?

### ISSUE THREAD

**Issue by ryan-mccaffrey** [guyonroche/exceljs#155]
I have a bunch of cells that contain different decimal numbers (all to two decimal places), but all of the cells that have decimals ending in a 0 (i.e. 1.80, 2.00) will not display the 0s (1.8 and 2 respectively). Is there a property in the library that can format the cell's number of decimal places? (In Excel, this can be accomplished by going to Format Cell -> Number -> edit 'Decimal places')

**Comment by ryan-mccaffrey** [comment]
Resolved using the numFmt property in the 'Number Formats' section of the readme. Set numFmt = '0.00' to indicate two decimal places.

**Comment by PriyankaChauhan06** [comment]
Input Number must be integer. so you can set numFmt = '0.00"%"'
