### ISSUE TITLE
exceljs might be vulnerable for regular expression denial of service

### ISSUE THREAD

**Issue by yonjah** [guyonroche/exceljs#164]
Runnig nsp check I get the following warning - 
Regular Expression Denial of Service 
minimatch 
exceljs@0.2.12 > archiver@0.14.3 > glob@4.3.5 > minimatch@2.0.10
https://nodesecurity.io/advisories/118

Not sure how big of an issue it is, but It might be best to upgrade the archiver package to the latest one (which in turn will upgrade glob and minimatch).

**Comment by guyonroche** [comment]
Oddly, I noticed this a few days ago too (must have watched the same video).
I'll push the recommended fix into the next release

**Comment by guyonroche** [comment]
Fixed in 0.2.13
