### ISSUE TITLE
Excel file is not created nor saved

### ISSUE THREAD

**Issue by neeraj87** [guyonroche/exceljs#169]
I am following the documentation to create an excel workbook and add worksheet to it. This is my code:

```
var Excel = require('exceljs');
        var workbook = new Excel.Workbook();
        var worksheet = workbook.addWorksheet('My Sheet');
        worksheet.columns = [
            { header: 'Id', key: 'id', width: 10 },
            { header: 'Name', key: 'name', width: 32 },
            { header: 'D.O.B.', key: 'DOB', width: 10 }
        ];
        worksheet.addRow({id: 1, name: 'John Doe', dob: new Date(1970,1,1)});
        worksheet.addRow({id: 2, name: 'Jane Doe', dob: new Date(1965,1,7)});
        workbook.commit();
        workbook.xlsx.writeFile('./temp.xlsx').then(function() {
            // done
            console.log('file is written');
        });
```

However, it does not create any excel file. Nothing happens. What am I doing wrong here?

**Comment by SPlatten** [comment]
Have you tried without the path prefix ?  This works for me:

        workbook.xlsx.writeFile("temp.xlsx");

**Comment by neeraj87** [comment]
Yes, I tried that. Nothing happens. The last console - "file is written" is never executed.

**Comment by SPlatten** [comment]
Have you verified that the object is being create correctly?  try surround the writeFile in a try catch clause.

**Comment by neeraj87** [comment]
Yup, there was an error: 

`TypeError: Object #<Object> has no method 'commit'`

Apparently, workbook.commit() or worksheet.commit() does not work. I don't know why it is in the docs. I just commented the workbook.commit() and it saved the temp.xlsx file in the node js project folder. I want the app to ask the user where to save it, how do I do it?

**Comment by SPlatten** [comment]
That's a much bigger problem., node is running on a server which may or may not be local to the client, you will have to either write something that runs in the browser, such as a form with a file selector or an application that can communicate with node using sockets.

**Comment by neeraj87** [comment]
So in case this application was not running on a local machine, where would it save the created file? Can you provide me some resources/links which I can use for this?

**Comment by SPlatten** [comment]
The file will be save on the file system of the system hosting node.  The root directory '/' refers to the base folder of the application that node is running.  As far as resources go, use http://www.w3schools.com and jquery.

**Comment by neeraj87** [comment]
Thank you. I will look into it.

**Comment by neeraj87** [comment]
Its working finally. 

```
try {
        var workbook = new Excel.Workbook();
        var worksheet = workbook.addWorksheet('My Sheet');

        worksheet.columns = [
            { header: 'Id', key: 'id', width: 10 },
            { header: 'Name', key: 'name', width: 32 },
            { header: 'D.O.B.', key: 'DOB', width: 10 }
        ];
        worksheet.addRow({id: 1, name: 'John Doe', dob: new Date(1970,1,1)});
        worksheet.addRow({id: 2, name: 'Jane Doe', dob: new Date(1965,1,7)});

        var tempFilePath = tempfile('.xlsx');
        workbook.xlsx.writeFile(tempFilePath).then(function() {
            console.log('file is written');
            res.sendFile(tempFilePath, function(err){
                console.log('---------- error downloading file: ' + err);
            });
        });
    } catch(err) {
        console.log('OOOOOOO this is the error: ' + err);
    }
```

**Comment by esinecan** [comment]
This isn't the same though. You're not using streaming api anymore.
