### ISSUE TITLE
how to use createAndFillWorkbook()?

### ISSUE THREAD

**Issue by xxryan1234** [guyonroche/exceljs#17]
Hi is there a demo on using createAndFillWorkbook()? a jsfiddle perhaps?

I get this error

        /Users/gzRyan/Documents/reports-observation/server.js:13

        TypeError: Object #<Object> has no method 'createAndFillWorkbook'

**Comment by xxryan1234** [comment]
created a question in stackoverflow
http://stackoverflow.com/questions/29933897/how-to-use-createandfillworkbook-in-exceljs

**Comment by guyonroche** [comment]
Apologies for taking so long to answer - I've been bogged down with other things and working on a streaming xlsx writer.
You could take a look in the spec folder where there are several examples of creating and filling workbooks.

**Comment by jckim0414** [comment]
I just answered your stackoverflow.

hope to help following sample source...

// create workbook by api.
var workbook = new Excel.Workbook();

// must create one more sheet.
var sheet = workbook.addWorksheet("My Sheet");

// you can create xlsx file now.
workbook.xlsx.writeFile("C:\\somepath\\some.xlsx").then(function() {
    console.log("xls file is written.");
});

**Comment by xxryan1234** [comment]
Thanks!
