### ISSUE TITLE
Data Validation Not working.

### ISSUE THREAD

**Issue by sagarjumble** [guyonroche/exceljs#174]
Hey ,

I have added data validation to my cell, but it doesn't open in MS Office 2010 or greater.
Also similar problems while opening it using open office.
However,  it works fine in Goog Sheets.

Can you please help me resolving this issue. It is very high priority for me.

**Comment by sagarjumble** [comment]
It also doesn't work in office 2007.
Any urgent help would be appreaciated

**Comment by sagarjumble** [comment]
Hey the issue is that my data validation list content length is greater than 255 character.
Can you please let me know how can we bypass it.

**Comment by guyonroche** [comment]
Hi @sagarjumble Could you post some demo code that reproduces the issue? It will make it much easier for me to debug. Thanks

**Comment by sagarjumble** [comment]
Hi @guyonroche I have resolved the above issue.
The issue was the drop-down characters were greater than 255 character length.
We have used formula and picked the drop-down values from a hidden cell.
