### ISSUE TITLE
Unexpected xml node in parseOpen

### ISSUE THREAD

**Issue by PRR24** [guyonroche/exceljs#176]
If xlsx is saved with LibreOffice, exceljs fails to upen it with
Fatal uncaughtException:  Error: Unexpected xml node in parseOpen: {"name":"dc:description","attributes":{},"isSelfClosing":false}
    at utils.inherits.parseOpen (node_modules/exceljs/lib/xlsx/xform/core/core-xform.js:89:17)
    at SAXStream.<anonymous> (node_modules/exceljs/lib/xlsx/xform/base-xform.js:65:14)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:188:7)
...

**Comment by guyonroche** [comment]
Could you attach a sample xlsx file that shows this?

**Comment by PRR24** [comment]
[LibreProblem.xlsx](https://github.com/guyonroche/exceljs/files/456060/LibreProblem.xlsx)

**Comment by PRR24** [comment]
As a connected question -- what would be the proper way how to catch such errors while streaming the workbook in? Currently my streaming looks following and the exception will not end up in 'error'.

var workbook = new Excel.Workbook();
let excelStream = workbook.xlsx.createInputStream();
excelStream.on('done', () => {
  // ...
});
excelStream.on('error', () => {
  // ...
});
stream.pipe(excelStream);

**Comment by jessica-jordan** [comment]
Having the same issue with a file edited and saved in LibreOffice right now. The file worked nicely with my exceljs formatting process before when it was still in the official MS Excel .xlsx format and not edited with LibreOffice. 
Would be great if someone has time to look at this one!

**Comment by tngTUDOR** [comment]
I also have this issue with libre office 5.1.4.2

**Comment by jessica-jordan** [comment]
@tngTUDOR Can you post the error warning that you get in your case to this issue?

**Comment by ivaylonikolov7** [comment]
I also have this issue. If the file is saved with libre office I get Error: Unexpected xml node in parseOpen: {"name":"cp:revision","attributes":{},"isSelfClosing":false}
    at utils.inherits.parseOpen 

I would be really glad if you can do something about it. Thank you.

**Comment by jessica-jordan** [comment]
@ivaylonikolov7 should be fixed with https://github.com/guyonroche/exceljs/commit/d0f51cd1e94d64b47fc1315b46061eadb83f1086

**Comment by guyonroche** [comment]
I have included the sample LibreOffice document in the integration tests and thanks to @jessica-jordan 's PR, it's fixed now.

**Comment by jessica-jordan** [comment]
Thanks @guyonroche for the addition, I'll add a test case should I open another PR in the future!

**Comment by janantala** [comment]
Hello, I have the same issue on Microsoft 365 exported xlsx
```
Error: Unexpected xml node in parseOpen: {"name":"x14:filter","attributes":{"val":"‘blue team tasks’ means tasks that are typically carried out by the blue team such as security operation centre (SOC), ICT infrastructure services, helpdesk services, incident management services at operational level;"},"isSelfClosing":true}
```
