### ISSUE TITLE
requiring exceljs causes 'Cannot find module bluebird' error

### ISSUE THREAD

**Issue by barbalex** [guyonroche/exceljs#188]
I can run my electron app in dev mode without errors.

When I build a release and start the app, this error appears:

```
Uncaught Error: Cannot find module 'bluebird' (module.js:457)
```

The error does not appear when I comment out the lines requiring exceljs and using it in one single module that is not run at the app start.

If the only thing that I change in that module is requiring exceljs, that causes the error.

This is that module: https://gist.github.com/barbalex/b566e18c3f51fad6aff956adfeae432d

What I have tried:
- loading bluebird and enclosing the `workbook.xlsx.writeFile` call in a bluebird promise
- deleting the node_modules folder and reinstalling all node_modules

I am using:
- windows 10
- node 6.5.0
- npm 3.10.3
- this is my package.json: https://gist.github.com/barbalex/fb4117e3cf2f0391e6c5295bf2434c03

**Comment by guyonroche** [comment]
Hi @barbalex 
It's difficult to say what's going on. In understand you might be sensitive about exposing too much of your code but could you reduce the problem to a demo app that exhibits the problem?
I did notice that you have express listed as a devDependency - could that be related?

**Comment by barbalex** [comment]
Hi @guyonroche 

I used [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) to start this project. I believe express is used as dev server.

I kept this project private until now but really it does not have to be. So I just opened it: https://github.com/barbalex/kapla

I am going on vacation now. Maybe you can have a quick look at the project. If not I will try to build a simple new project that hopefully can demo this effect in two or three weeks.

Trouble is: this was my first electron project. So building a simple one without using a boilerplate will not be that simple to me. But as this error needs to be solved I will dive into it.

**Comment by barbalex** [comment]
closing this because the issue got solved: electron-react-boilerplate has a new build system and the error does not occur any more :-)
