### ISSUE TITLE
Problem in ubuntu but not in windows

### ISSUE THREAD

**Issue by Timespace7** [guyonroche/exceljs#2]
I'm using a pc with windows 7 for development and a server with ubuntu for production.
There is no problem in windows node.js to generate .xlsx files. However, it is possible to generate some damaged .xlsx files in ubuntu node.js. 

When the damaged file is opened, a error is shown: "Excel found unreadable content in *******.xls. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click yes".

I have no idea at all about the error. I found the file size generated in window and ubuntu are not same. I guess there is a problem during writing the file or zipping it.

**Comment by guyonroche** [comment]
Hi, it will take me some time to test this on Linux - do you have a sample xlsx file I could take a look at? It might point out what is going wrong. You can email it to cyber.sapiens@hotmail.com.
Thanks,
Guyon

**Comment by guyonroche** [comment]
Finally got around to trying it out on Ubuntu (14.04.1) with node (v0.10.25)  and couldn't reproduce the problem. There's a chance this may have been an xml-escaping issue, I've fixed a few of these in the past couple of weeks. Could you npm update to latest (exceljs@0.1.1) and try again?

**Comment by guyonroche** [comment]
Or even better, try exceljs@0.1.2 - I found a potential race condition at the end of the zip write.

**Comment by guyonroche** [comment]
Haven't had much feedback on this issue so I'm going to leave it open for one more week and then close as not reproduced.

**Comment by shamere** [comment]
^اطنخ^

**Comment by shamere** [comment]
7

**Comment by shamere** [comment]
https://github.com/shamere/-/commit/555756bc9f41d2529c6495e69ae546b40941278c

**Comment by guyonroche** [comment]
Closing due to lack of response. 
I have introduced an ubuntu test in my "release plan" so hopefully this issue won't arise again.

**Comment by sanarockings** [comment]
But i have problem, in windows  64 bit.

fatal: cannot create directory at 'node_modules/node-xlsx/node_modules/lodash.map/node_modules/lodash.createcallback/node_modules/lodash._basecreatecallback/node_modules/lodash.bind/node_modules/lodash._createwrapper/node_modules/lodash._basebind/node_modules': No such file or directory

Can you please help me?

**Comment by ipsita93** [comment]
I have a problem while running on Linux machine. I get the following error:

Unhandled rejection Error: ENOENT: no such file or directory, open '/var/app/current/controllers/files/template_51_NUS_School_of_Computing.xlsx'
    at Error (native)

How do I make the " workbook.xlsx.writeFile(child_file_name)" work on Linux machines?
