### ISSUE TITLE
Write to binary?

### ISSUE THREAD

**Issue by idrakimuhamad** [guyonroche/exceljs#20]
Is there a way to do this? For example, if I want to write the file into buffer/binary which then I can use it for some other stuff. I know there're write to stream, but not sure how can I do it or get the binary written.

Something like in SheetJS, `XLSX.writeFile(workbook, { type: 'binary' });` will write the file in binary. Is there something for this?

Thanks for you work

**Comment by guyonroche** [comment]
I'm not entirely sure what you mean. The XLSX file format is binary (actually it's a zip of xml files).
If you're after a memory buffer of the xlsx data you could do something like this.

```javascript
var Excel = require("exceljs");
var unstream = require('unstream');

var workbook = new Excel.Workbook();

// fill in worksheet(s) with data

// then write it through unstream to a buffer
workbook.xlsx.write(unstream({}, function(data) {
    // data is your buffer
  });
```

Please note, I haven't had any experience using unstream. 
If that doesn't work you could swipe the [StreamBuf](https://github.com/guyonroche/exceljs/blob/master/lib/utils/stream-buf.js) class from exceljs...

```javascript
var buf = new StreamBuf()
workbook.xlsx.write(buf)
  .then(function() {
    var data = buf.toBuffer();
  });
```

**Comment by idrakimuhamad** [comment]
Yeah that's what I meant. I need it in buffer so I can use it for something else. That's perfect.

**Comment by piyushsf** [comment]
workbook.xlsx.write(unstream({}, function(data) {
    // data is your buffer
  });

The above mentioned code works perfectly. I was wondering if there is a  way to handle error in this case?

**Comment by chunkjs** [comment]
Hello, is there an updated example that will give me the workbook in a buffer?  I'm getting an error when initializing the StreamBuf, thanks in advance!
