### ISSUE TITLE
how can i write a new line character into a cell

### ISSUE THREAD

**Issue by wwj559** [guyonroche/exceljs#207]
tried some string like 'abc\nxyz' , it does not work

**Comment by dferer** [comment]
According to a closed issue, '\r\n' worked a few versions ago but it won't work in the current version (0.2.39).
The text is displayed on one line until double-clicked/edited.

**Comment by dferer** [comment]
It works if you:
* set  '\r\n' as the line separator
* apply alignment: { wrapText: true } to the cell.

**Comment by jayflores** [comment]
what @dferer mentions does not work for me.

**Comment by Rycochet** [comment]
@jayflores It won't, those characters are stripped out of the file when saving, hence my pull request that fixes it...

**Comment by jayflores** [comment]
@Rycochet yeah I saw it.  Was just commenting here as an FYI for others who might read @dferer 's comment.
