### ISSUE TITLE
can we write it in to the existing xlsx

### ISSUE THREAD

**Issue by sandeepSathish** [guyonroche/exceljs#21]
how to write in to the existing workbook without creating new workbook...

**Comment by guyonroche** [comment]
You can open the xlsx file, make your modifications so the workbook/sheets and then write back to the same filename.

e.g. 
```javascript
var workbook = new Excel.Workbook();
workbook.xlsx.readFile(filename)
  .then(function() {
    // edit worksheet
    var worksheet = workbook.getWorksheet("My Sheet");
    worksheet.getCell("A1") = new Date();
  })
  .then(function() {
   return workbook.xlsx.writeFile(filename)
  })
  .then(function() {
    console.log("Done");
  });

```

**Comment by sandeepSathish** [comment]
![capture](https://cloud.githubusercontent.com/assets/13032708/8474069/82827468-20cb-11e5-9f99-f9b502697f55.PNG)


I'm getting this error while writing in to the excel sheet...

**Comment by miha-plesko** [comment]
**@guyonroche** shouldn't it be:

```
worksheet.getCell("A1").value = new Date();
```

instead of

```
worksheet.getCell("A1")= new Date();
```
?

**Comment by Blakey** [comment]
Hi,

Is there a way to do something similar in stream mode? i.e. I am currenlty using **_new Excel.stream.xlsx.WorkbookWriter(options)_** to stream SQL data into a new spreadsheet and it is very successful. However I want to be able to use an existing template that has pivot tables, charts, conditional formatting, etc and then just stream data into the respective Data sheet of this workbook.

The template will usually be very small in size, so memory shouldnt be an issue. I just want to use the template and stream to it.

Any idea how to achieve this?

Thanks

**Comment by elliotpj** [comment]
+1 Is there any update on this? This would be great to have!

**Comment by jasonbarrows** [comment]
I have managed to load a remote spreadsheet, make updates and offer the file as a download all from the browser so I am posting the code in case its of use to anybody.

```javascript
// Additional libraries required: 'jszip', 'FileSaver'

axios.get('/path/to/file.xlsx', { 
    responseType: 'blob',
    headers: { 'content-type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }
}).then((response) => {
    const fileReader = new FileReader()

    fileReader.onload = function() {
        const typedArray = new Uint8Array(this.result)
        JSZip.loadAsync(typedArray).then(() => {
            const workbook = new Excel.Workbook()
            workbook.xlsx.load(this.result).then(() => {
                const ws = workbook.getWorksheet('Sheet Name')
                // Add details to sheet here
            }).then(() => {
                workbook.xlsx.writeBuffer().then(data => {
                    const blob = new Blob([data], { type: this.blobType })
                    FileSaver.saveAs(blob, 'new-file-name.xlsx')
                })
            })
        })
    }

    fileReader.readAsArrayBuffer(new Blob([response.data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }))
})
```

**Comment by phongtranao** [comment]
Hi,
You should pass workbook object after file read.
and getCell method with row and colum as parameters.

Example: _(enviroment: node: v14.3.0; exceljs: ^4.2.0)_
i open a existed workboox, open first sheet and get value of first cell.

`await workbook.xlsx.readFile(`<path>/myexcel.xlsx`).then(async (w) => {
            const worksheet = w.getWorksheet(1);
            const a1 = worksheet.getCell(1, 1).value;
            console.log(a1);
        });`

It work good for me.

**Comment by phongtranao** [comment]
Hi,
You should pass workbook object after file read.
and getCell method with row and colum as parameters.

Example: _(enviroment: node: v14.3.0; exceljs: ^4.2.0)_
i open a existed workboox, open first sheet and get value of first cell.

```
await workbook.xlsx.readFile(`${<path>}report-13-t.xlsx`).then(async (w) => {
            const worksheet = w.getWorksheet(1);
            worksheet.getCell(1, 1).value = new Date();
            const a1 = worksheet.getCell(1, 1).value;
            await w.xlsx.writeFile(`${<path>}report-13-t.xlsx`);
            console.log(a1);
});
```

It work good for me.
