### ISSUE TITLE
multiple sheet csv can't support ???

### ISSUE THREAD

**Issue by sunyue1992** [guyonroche/exceljs#215]
`
var worksheet1 = workbook.addWorksheet('sheet1',{properties: {tabColor: {argb: 'FF00FF00'}}})
var worksheet2 = workbook.addWorksheet('sheet2',{properties: {tabColor: {argb: 'FF00FF00'}}})

worksheet1.addRows([[3,'bob',new Date()],[1,2,3]]);
worksheet2.addRows([[4,'Sam',new Date()]]);

workbook.eachSheet(function(worksheet, sheetId) {
    console.log(worksheet)
});

var st = fs.createWriteStream('demo.csv');

workbook.csv.write(st)
`

but csv result is 
![democsv](https://cloud.githubusercontent.com/assets/9960131/19916134/46eb067e-a0f2-11e6-8b71-e8a9f2a373b6.png)

**Comment by sunyue1992** [comment]
but multiple xlsx is work 
`var worksheet1 = workbook.addWorksheet('sheet1',{properties: {tabColor: {argb: 'FF00FF00'}}})
var worksheet2 = workbook.addWorksheet('sheet2',{properties: {tabColor: {argb: 'FF00FF00'}}})

worksheet1.addRows([[3,'bob',new Date()],[1,2,3]]);
worksheet2.addRows([[4,'Sam',new Date()]]);


workbook.eachSheet(function(worksheet, sheetId) {
    console.log(worksheet)
});


var st = fs.createWriteStream('demo.xlsx');

workbook.xlsx.write(st)`

![demosheet](https://cloud.githubusercontent.com/assets/9960131/19916160/82c9f812-a0f2-11e6-941f-d471e599aded.png)

**Comment by dvsoukup** [comment]
+1.  I concur with this bug... I ran into the same problem.  Just wound up using xlsx format instead, but had to "hack" around the data by first converting everything from a CSV format and rewrite file into an xlsx.  Works but just added time to what I needed to get done.

**Comment by kgajowy** [comment]
I would not consider this a bug. Even though CSV if quite far away from being `standardized` it generally corresponds to "single entity" representation - which means, it cannot have more than one tab. Please consider CSV == CommaSeparatedValues - there is not place for multiple sheets.

**Comment by sunyue1992** [comment]
@kgajowy thanks,you are right

**Comment by darshanksexathought** [comment]
@kgajowy  but if you open a csv there you have an option to add another sheet , then why cant we have that feature in this package?
