### ISSUE TITLE
Is there any way to link a cell in a workbook?

### ISSUE THREAD

**Issue by srain** [guyonroche/exceljs#216]
Sorry to trouble you. 

I'm looking for a way to link a cell to a cell in a workbook, is there any idea?

Detail screenshot:
![2016-11-03_15h39_17](https://cloud.githubusercontent.com/assets/4929763/19958625/b268378e-a1db-11e6-83de-076c08b1e82e.jpg)

**Comment by srain** [comment]
this issue has been fixed, I find a formula to realize it.
```
row.getCell(1).value = {
    formula: 'HYPERLINK("#1.1!c1","1")',
    result: '1.1'
}
```
So, I closed it.

**Comment by smalltalk-josh** [comment]
FYI, there is another way to to do this using the hyperlink format.
The key is to use the `#` to reference the workbook, then you just reference the sheet and cells normally.

```javascript
row.getCell(1).value = {
    hyperlink: '#1.1!c1',
    text: '1.1'
}
```

**Comment by Diluka** [comment]
> ```js
> row.getCell(1).value = {
>     hyperlink: '#1.1!c1',
>     text: '1.1'
> }
> ```

This is working and the example in `README.md` isn't 
https://github.com/exceljs/exceljs#hyperlink-value
@guyonroche
