### ISSUE TITLE
cannot read propeety getcell of undefined..

### ISSUE THREAD

**Issue by sandeepSathish** [guyonroche/exceljs#22]
![capture](https://cloud.githubusercontent.com/assets/13032708/8474134/dc1445ce-20cb-11e5-911c-0325518c2610.PNG)

**Comment by guyonroche** [comment]
Any chance you could reproduce this in a small test app?

**Comment by guyonroche** [comment]
This issue duplicated [Here](https://github.com/guyonroche/exceljs/issues/23)
