### ISSUE TITLE
Using solid fill causes malformed xlsx file

### ISSUE THREAD

**Issue by lrecknagel** [guyonroche/exceljs#239]
First thanks for the nice lib :) 👍 

But I have a problem when I try to set a fill style on each even row.

If I create several rows, add then to a sheet with:
```js
sheet.addRows(_rows);
```

and then set the style:

```js
sheet.eachRow( (row, idx) => {
    let _fill = {}
    if (idx % 2 == 0) {
        _fill.type = 'pattern'
        _fill.pattern = 'solid'
        _fill.fgColor = {argb: 'F046B8DA'}
    }
    row.fill = _fill
})
```

=> Output is mal formed ...

If I only set borders:

```js
sheet.eachRow( (row, idx) => {
    let _border = {}
    if (idx % 2 == 0) {
        _border.bottom = { style: 'double', color: {argb: 'F046B8DA'}}
    }
    row.border = _border
})
```

Produces a valid xlsx file.

Any ideas what I don´t get or where to search for the issue?!

**Comment by lrecknagel** [comment]
Solved it:

```
sheet.eachRow( (row, idx) => {
    let _fill = {type: 'pattern', pattern: 'solid', fgColor: {argb: 'FFFFFFFF'}}
    if (idx % 2 == 0) {
      _fill.fgColor = {argb: '0046B8DA'}
    }
    row.fill = _fill
  })
```

Sorry for that issue ...

**Comment by StephanMeijer** [comment]
What was exactly the issue and how did you solve this?

**Comment by lrecknagel** [comment]
The issue was that I set an empty object for row.fill which is not valid.
In my solution, as posted above, I define _fill with default params and only modify the fgColor when needed. Hope this helps ;)
