### ISSUE TITLE
Read content from xlsx file. 

### ISSUE THREAD

**Issue by chetanmekha** [guyonroche/exceljs#243]
Hello Mates,
I want to read .xlsx file from my application. I am able to parse the file with help of below code.
`var Excel = require('exceljs');
var workbook = new Excel.Workbook();
workbook.xlsx.readFile('ccsdemoquestions.xlsx')
    .then(function(data) {
        // use workbook
         console.error("else data: " + data); 
    });` 

Where can i get excels column values in data object?
Please guide me on the same.

**Comment by neeraj87** [comment]
You have to read the worksheet present within the workbook. You will get "rows" from the worksheet. So something like this:

```
var inboundWorkbook = new Excel.Workbook();
var inboundWorksheet = inboundWorkbook.getWorksheet(1); //or name of the worksheet
inboundWorkbook.xlsx.readFile(req.file.path).then(function() {
   inboundWorksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) {
	console.log("Row " + rowNumber + " = " + JSON.stringify(row.values));
   });
});
```

**Comment by chetanmekha** [comment]
I have implemented like this,
`var XLSX = require('xlsx');
var workbook = XLSX.readFile('ccsdemoquestions_CM.xlsx');`
`var itemToSave={
    'tags':"",
    'subCategoryId':"",
    'entryId':"",
    'Question':"",
    'Answer' : ""

};
var dataarray = [];
for (var count = 1; count < 27; count++) {
    console.error(workbook.Sheets.Sheet1['A'+count].v);
    // console.error(workbook.Sheets.Sheet1['B'+count].v);
    // console.error(workbook.Sheets.Sheet1['C'+count].v);
    itemToSave.tags = workbook.Sheets.Sheet1['A' + count].v;
    itemToSave.subCategoryId = workbook.Sheets.Sheet1['B' + count].v;
    itemToSave.entryId = workbook.Sheets.Sheet1['C' + count].v;
    itemToSave.Question = workbook.Sheets.Sheet1['D' + count].v;
    itemToSave.Answer = workbook.Sheets.Sheet1['E' + count].v;
}`

**Comment by hazemsamoaa** [comment]
@neeraj87 
I apply the same of your code 

`var Excel = require('exceljs'); var inboundWorkbook = new Excel.Workbook(); inboundWorkbook.xlsx.readFile("Data/DataSet.xls").then(function() { var inboundWorksheet = inboundWorkbook.getWorksheet(1); //or name of the worksheet inboundWorksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) { console.log("Row " + rowNumber + " = " + JSON.stringify(row.values)); }); });`

but I got the error TypeError: Cannot read property 'eachRow'
I work in version exceljs@1.5.0, so I update eachrow function exactly like the documentation but still doesn't work
