### ISSUE TITLE
Add a "hidden" property to column and row?

### ISSUE THREAD

**Issue by adelimon** [guyonroche/exceljs#26]
While using the library, I found a use case for hiding a column.  IDs that I didn't want/need my users to see, but still needed in the uploaded spreadsheet when they were done working with it.

I was able to achieve this by setting width to zero.  However, a hidden property could be potentially useful.

I started to create a pull request containing that seemingly simple code.  But, then I realized that this could cause conflicts with the "Width" property, and wasn't sure how to handle it.  so I thought I could open this for discussion.

**Comment by guyonroche** [comment]
It looks quite simple - no need to mess with the widths or heights. I'm hoping to get back to working on this soon. I'll add this feature in.

**Comment by guyonroche** [comment]
Done. In v0.2.4
Both Row and Column now support a .hidden property
