### ISSUE TITLE
addWorksheet cannot accept ampersand chararcters

### ISSUE THREAD

**Issue by bchr02** [guyonroche/exceljs#27]
Just starting out with exceljs and lost about 30 minutes trying to figure out why I kept getting corrupt excel files. It turns out the issue was because of an ampersand character in the worksheet name. In excel, these are allowed so I guess I assumed they would work.

For example, the following generates a corrupt workbook: workbook.addWorksheet("hello & bye");

**Comment by guyonroche** [comment]
Apologies for the delay. This probably just needs xml escaping on the worksheet name.
I'll look into it

**Comment by guyonroche** [comment]
Finally - Fixed in 0.2.4!

**Comment by bchr02** [comment]
Thank you!!!
