### ISSUE TITLE
Column, row and cell styles priority mismatch?

### ISSUE THREAD

**Issue by akryvda** [guyonroche/exceljs#271]
Desired behaviour:
column headers should have 
`alignment: {
	textRotation: 45
},`
Rest of the rows should not.
When i apply above style to the columns, then setting
`alignment: {
	textRotation: 0
},`
to the rows - row styles are not taken into account.
I have to add a row, and add an extra iteration to the each of row's cells to apply styling to each of these cells.
With typical 500-1000 columns in the generated xlsx this does include both processing time and resulting file size drastically.

Are there any way to reset orientation row-wide?

**Comment by Rycochet** [comment]
Why not just go through the header row once and add the `textRotation` to that, rather than adding to the entire column?
