### ISSUE TITLE
Expand text with line break symbols

### ISSUE THREAD

**Issue by pyatskevich** [guyonroche/exceljs#274]
I have a value in column with line break symbols, after file was created, value show in one line, but when I double click it expand 
Line before double click - http://take.ms/AEh88
After - http://take.ms/nbaj8
**Is it possible to generate it like in second picture?**
Also if make set height 150px it show value in one line anyway
For line break I am using symbols '\r\n'
p.s. line break work in version 0.2.33(maybe other to, not test it) but not in 0.3.0

**Comment by adsoftware** [comment]
Same here in 0.2.33.
This only happens in Excel, LibreOffice is fine

**Comment by shivavelingker** [comment]
My \n's still seem to get stripped out when saving the file, even if I made no changes to the file. I'm using v0.4.11. Am I overlooking how the fix was implemented?

**Comment by tonsquemike** [comment]
Hi, I still having this issue on v4.1.1. any suggestion?
