### ISSUE TITLE
   Xlsx invalid signature: 0x80014

### ISSUE THREAD

**Issue by skariuki** [guyonroche/exceljs#28]
Am getting an invalid signature: 0x80014 when reading an excel sheet that has 1 worksheet and 1443 rows, 8 cols to data. For some reason, this error starts been generated when the excel sheet has more than 1370 rows of data. 

Any ideas?

**Comment by hasanlussa** [comment]
https://github.com/EvanOxfeld/node-unzip/issues/89

**Comment by gormat** [comment]
I changed unzip with unzip2 and all works well.
https://github.com/gormat/node-excelJS-fixed-unzip

**Comment by guyonroche** [comment]
Now published (0.2.6) with unzip2

**Comment by asherklein** [comment]
Hi! I'm having this issue again, thanks

**Comment by nitsshukla** [comment]
same here, file was created by exceljs. But if i try to read it again without making any modification, it doesn't work.
