### ISSUE TITLE
Add columns names based on key values

### ISSUE THREAD

**Issue by jgoux** [guyonroche/exceljs#29]
Hello,
would it be possible to add an option to write the column names of a worksheet based on the keys of the first row added to it ?
For example : 
```js
const worksheet = workbook.addWorksheet("test", { columns: true })
worksheet.addRow({username: "foo", email: "bar@baz.com"}).commit()
worksheet.addRow({username: "bar", email: "foo@foz.com"}).commit()
worksheet.commit()
```
Then the worksheet's columns would be "username" and "email".

The case for this is streaming from multiple sources (same structure of data, this is a sql query actually) into the same file.

EDIT : Nevermind, it's easily done in userland : 
```js
if (!worksheet.columns) {
    worksheet.columns = Object.keys(row).map((k) => ({ header: k, key: k }))
}
```

**Comment by Utsaww** [comment]
Hi, could you please help me with this I am also trying to print labels.

**labels array are like this** - 

    [
      'Type',
      'Competition',
      'IDB',
      'SOV Focus',
      'Medium',
      'Tone'
    ]

So, I only need to print these in the header.

```
          con.query(query, id, function (err, result) {
          if (err) throw err;
          const labels = [];
          result.forEach((result) => {
            labels.push(result.label);
          });
          labels.forEach((label, index) => {
            const columnName = label;

            // Get the column using the column index (in this case, 1)
            const firstRow = worksheet.getRow(1);

            // Set the value of the first cell in the row to the dynamic column name
            firstRow.getCell(36, columnName);
          });
        });
```
