### ISSUE TITLE
Problem with more than 9 sheet

### ISSUE THREAD

**Issue by i3fox** [guyonroche/exceljs#3]
With an .xlsx file with more than 9 sheets crashes.

For resolve the problem in regular expressions I changed \d with \d+

default:
    if (entry.path.match(/xl\/worksheets\/sheet\d+\.xml/)) {
        var match = entry.path.match(/xl\/worksheets\/sheet(\d+)\.xml/)
        var sheetNo = match[1];
        promise = self.parseWorksheet(entry)
            .then(function(worksheet) {
                worksheet.sheetNo = sheetNo;
                model.worksheetHash[entry.path] = worksheet;
                model.worksheets.push(worksheet);
            });
    } else if (entry.path.match(/xl\/worksheets\/_rels\/sheet\d+\.xml.rels/)) {
        var match = entry.path.match(/xl\/worksheets\/_rels\/sheet(\d+)\.xml.rels/)
        var sheetNo = match[1];
        promise = self.parseRels(entry)
            .then(function(relationships) {
                model.worksheetRels[sheetNo] = relationships;
            });
    } else {
        entry.autodrain();
    }
    break;

is correct?
Thanks

**Comment by guyonroche** [comment]
D'oh! Yes, nice find. And your suggested fix is spot on too.
Just published 0.1.5 including this fix.
