### ISSUE TITLE
No Node is Good News

### ISSUE THREAD

**Issue by acgentry** [guyonroche/exceljs#31]
Pardon the stupid question, my assumption is that this project only works within node, is there anyway to make this a purely client side project (akin to xlsxjs)? 

To clarify, when using browserify the module in a non-node project getting the following error:
process.binding is not supported

So my assumption is that it must use node for file system access, it would be great if there is a shim/factory pattern that would allow me to use a serialized file object in the browser.

Thanks in advance!

**Comment by DanlanNZ** [comment]
:+1: I'm also having this trouble in an universal/isomorphic app, would be great if there was a workaround

**Comment by RudolfVonKrugstein** [comment]
+1

**Comment by DanlanNZ** [comment]
ended up using this library instead, https://github.com/JoseBarrios/async-xlsx features aren't as good as exceljs but it works on both client and server

**Comment by guyonroche** [comment]
I agree, browserifying would be a good plus. The big thing working against me is free time.
I've added it to my TODO list

**Comment by saadq** [comment]
I would also be eternally grateful if you Browserified this. I think this module has the easiest API and makes it very easy to style. I've been trying to write a chrome extension that creates and then downloads an excel file, and the other client-side xls modules don't seem to really work well with Browserify.

**Comment by yoannpe** [comment]
I also think that an non-node version of your library will be very useful for a lot of people :)

**Comment by seanodotcom** [comment]
+1 for straight-up JS (the way most people are still doing it)

**Comment by fredguth** [comment]
+1

**Comment by kachkaev** [comment]
This sounds like an awesome feature to have. Who is using what workarounds meanwhile guys?

**Comment by TimGeisler** [comment]
I would also use this library in a purely client-side project. We are currently using https://github.com/SheetJS/js-xlsx, which currently seems not to be maintained.

**Comment by saadq** [comment]
I ended up going with a bit more of a hacky solution, which is to generate a `.xls` file from an HTML table. Just google "html table to excel sheet jsfiddle" and there are several ways of doing it. And styles that you have on the `<tr>` or `<td>` elements will carry over to the excel sheet.

**Comment by ayedfaisel** [comment]
Any progress?

**Comment by st-sloth** [comment]
> We are currently using https://github.com/SheetJS/js-xlsx, which currently seems not to be maintained.

There is https://github.com/protobi/js-xlsx which is a fork from the original project and unlike the original it finally has cell styles and some other features.

But having exceljs for browser would be great.

**Comment by csvan** [comment]
+1

**Comment by jamatthew** [comment]
bump

**Comment by SaidMarar** [comment]
+1

**Comment by zont** [comment]
+1

**Comment by guyonroche** [comment]
Just to keep everyone informed - since this issue is a pain point for so many, I've decided to prioritise it.
It will require some effort to switch to a more browser friendly zip library... Stay tuned :-)

**Comment by aseem2625** [comment]
Has anyone got progress with this library. It's giving me following error,

```
@ ./~/exceljs/lib/stream/xlsx/worksheet-reader.js 25:9-22
[0] ./~/exceljs/lib/xlsx/xform/core/content-types-xform.js
[0] Module not found: Error: Cannot resolve 'file' or 'directory' ./empty_shim.js in /Users/myUser/Documents/projectName/node_modules/exceljs/lib/xlsx/xform/core
[0] resolve file
```

I'm already having empty_shim.js file in my root director or project. But anyways, it's finding inside the exceljs directory itself.

**Comment by akryvda** [comment]
Hi @guyonroche.
I've seen you have made commits into browserify branch. I have given it a try, though I'm getting errors at
{code}
var fs$ReadStream = fs.ReadStream
  ReadStream.prototype = Object.create(fs$ReadStream.prototype)
  ReadStream.prototype.open = ReadStream$open
{/code}
part of the bundled file.
Could you, please, clarify whether it's my setup fails or whatever?
Chrome 54,
$ node --version
v6.9.4

Thanks in advance!

**Comment by guyonroche** [comment]
Hi @akryvda 
no, it's not you - I was just trying to see if zip-stream would work but unfortunately not. For now I'll try again to make js-zip work. Soon as I have something that passes all the tests I'll update this issue

**Comment by guyonroche** [comment]
Finally! I can close this issue, browserify bundle now included in 0.2.41

**Comment by acgentry** [comment]
Awesome news, can't wait to use it on the next project, thanks @guyonroche !

**Comment by sskarabej** [comment]
Congrats for the browser version!
Do you plan to include workbook reader/writer any time soon? At this time, we get 

> Uncaught TypeError: fs.createWriteStream is not a function

 when trying to writeFile.

**Comment by guyonroche** [comment]
@sskarabej - I would like to add workbook reader/writer but the zip library I'm using to work in the browser (jszip) isn't properly streaming and so the whole benefit of the reader/writer of smaller memory footprint would be lost - which is why I haven't included them in the browser export.

**Comment by sskarabej** [comment]
@guyonroche thanks for (such fast) reply. I understand the issue, streaming mode is big advantage of your library.

**Comment by dmr** [comment]
This post has been open for a while --> What is the current solution you are using to achieve Excel in the frontend?

**Comment by jamatthew** [comment]
@dmr we explored options at the beginning of the year and ultimately settled on https://github.com/SheetJS/js-xlsx with https://github.com/handsontable/handsontable to read Excel files on the client side and allow customers to select a range for import.  Our import code is a modified version of their demo http://oss.sheetjs.com/

**Comment by leonardopolly** [comment]
@guyonroche any news on this?
