### ISSUE TITLE
Error reading in and then writing back a valid XLSX created using exceljs

### ISSUE THREAD

**Issue by stefandz** [guyonroche/exceljs#311]
I get an error with the following code:

```js var Excel = require('exceljs');
const fs = require('fs');
const testPath = './test.xlsx';

var sheetNames = [ 'one', 'two', 'three' ];

function initWorkbook ( path ){
  var workbook = new Excel.Workbook();
  var worksheet;
  return new Promise( function (resolve, reject ) {
      try {  
        if (fs.existsSync(path)) {
          console.log( "output exists" );
          workbook.xlsx.readFile( path );
          // load the Excel workbook but do nothing
        } else {
          console.log( "output doesn't exist" );
          sheetNames.forEach( function( value ){
            worksheet = workbook.addWorksheet(value);
          });
        }
        resolve( workbook );
      }
      catch( err ){
        reject();
      }
  });
}

initWorkbook( testPath )
.then( workbook => {
  workbook.xlsx.writeFile(testPath)
  .then(function() {
    console.log("all done");
  });  
}).catch( err => { 
  console.error( err );
});
```

This should check for the existence of `test.xlsx` and take one of two actions:

* if it doesn't exist, the program creates a valid Excel workbook with three sheets, labelled `one`, `two` and `three`
* if it does exist, we simply read that file in and write it back out again

This works correctly the first time around (creating the new file) and I can verify that it is a valid .xlsx file using Excel. The second run, however, I get this:

```bash node ./test.js
output exists
(node:5130) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
all done
```
The previously written file is now corrupt and unreadable by Excel. Exceljs is 0.4.4, node is 6.10.2

**Comment by guyonroche** [comment]
workbook.xlsx.readFile and workbook.xlsx.writeFile are async functions that return a Promise. When you call them, you need to wait for the promise to resolve.

**Comment by stefandz** [comment]
Thank you for this @guyonroche - my node-fu is weak and Promises doubly so! For anyone interested in future, this code functions correctly:

```js
var Excel = require('exceljs');
const fs = require('fs');
const testPath = './test.xlsx';

var sheetNames = [ 'one', 'two', 'three' ];

function initWorkbook ( path ){
  var workbook = new Excel.Workbook();
  var worksheet;
  return new Promise( function (resolve, reject ) {
      try {  
        if (fs.existsSync(path)) {
          console.log( "output exists" );
          // load the Excel workbook but do nothing
          workbook.xlsx.readFile( path ).then( function() {
            resolve( workbook );
          });
        } else {
          console.log( "output doesn't exist" );
          sheetNames.forEach( function( value ){
            worksheet = workbook.addWorksheet(value);
          });
          resolve( workbook );
        }
      }
      catch( err ){
        reject();
      }
  });
}

initWorkbook( testPath )
.then( workbook => {
  workbook.xlsx.writeFile(testPath)
  .then(function() {
    console.log("all done");
  });  
}).catch( err => { 
  console.error( err );
});
```

**Comment by hassanascend** [comment]
(node:71371) UnhandledPromiseRejectionWarning: Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at NodeBufferReader.checkIndex (/var/www/html/ticketingNodejs/server/node_modules/jszip/lib/reader/DataReader.js:26:19)
    at NodeBufferReader.checkOffset (/var/www/html/ticketingNodejs/server/node_modules/jszip/lib/reader/DataReader.js:17:14)
    at NodeBufferReader.readData (/var/www/html/ticketingNodejs/server/node_modules/jszip/lib/reader/NodeBufferReader.js:14:10)
    at NodeBufferReader.readString (/var/www/html/ticketingNodejs/server/node_modules/jszip/lib/reader/DataReader.js:75:49)
    at ZipEntries.isSignature (/var/www/html/ticketingNodejs/server/node_modules/jszip/lib/zipEntries.js:40:37)
 when data is more than 5k
