### ISSUE TITLE
Request for Opinion - Transpiling ExcelJS

### ISSUE THREAD

**Issue by guyonroche** [guyonroche/exceljs#314]
Hey Everyone,
ExcelJS has reached a point where it has to transpile the distributed code. Many users, for various reasons, are still using earlier versions of Node, yet I want to start taking advantage of the JavaScript features that will help make the code easier to read, maintain and so on.

First question is: what versions of Node are using this library? This will give me an idea on how much effort to put into compatibility. Currently I'm targeting 4.0.0 but if earlier is needed, it will need polyfills to cope with other missing features.

Second: Minified or not? Minifying the code reduced it to about 180kb and presumably will improve startup time. The function names are preserved so stack traces will still be meaningful but it could make debugging difficult.

I'll keep this issue open for a few days with the intent of publishing the result early next week

**Comment by Rycochet** [comment]
Personally I'd say target the LTS version of NodeJS - currently v6.10.3 - and if required have another version that is ES3 + polyfill complete to handle anything earlier than that (ie, two builds), then supply a minified version of each. I'm using it in the browser, so simply using the latest builds makes it nicer to keep the bandwidth down.

**Comment by guyonroche** [comment]
I'm keen to retain support of 4.x as it is clearly still in use and altough it may have just left LTS, it is still in 'maintenance'. It's also fairly easy to do and doesn't require polyfills (in particular Object.assign and Array.isArray)

**Comment by tjunnone** [comment]
Node: Tracking LTS (6.x currently), and always will be.

Minified: In my opinion, those who care about minification will have to handle it themselves anyway (since they're not only going to be depending on ExcelJS), and personally I'd rather be able to follow code references in my IDE into the non-minified sources (even if transpiled). I think it's quite rare to see a minified node module.

Thanks for all the great work!

**Comment by Rycochet** [comment]
Good point for minified nodejs modules - however having a minified version of the non-nodejs version in the repo means that CDN networks (I'd love to see this get on JSDelivr etc) can provide them for use in the browser.

**Comment by guyonroche** [comment]
I agree on the minifying. Also, with all the code in the dist folder, there's no need to publish the lib so that will keep the size down.
There is already a browserified & minified bundle published in dist so we're covered there.

**Comment by guyonroche** [comment]
Thanks for the input. 0.4.9 now released with transpiled dist folder.
