### ISSUE TITLE
One bug and one question

### ISSUE THREAD

**Issue by xy02** [guyonroche/exceljs#32]
Great Repo! Thank you for your contribution. You might as well add a keyword 'xlsx' into the description of this awesome repository for more people can find it via Search.
I found that the streaming XLSX writer has a bug
```javascript
worksheet.addRow({
   id: i,
   name: theName,
   etc: someOtherDetail
}).commit();
```
this do not work, but
```javascript
worksheet.addRow([ i, theName, someOtherDetail ]).commit();
```
this work.
And I have a question, how to set a hyperlink which link to a cell of another worksheet.

**Comment by guyonroche** [comment]
Apologies for taking so long to reply, I've had a pretty hectic workload lately.

Re: addRow - did you define the column keys?

Re: hyperlinks to cells - good question. I will take a look

**Comment by xy02** [comment]
My fault, miss column keys...

I mean the Description of Github setting. so guys can find this repository using search box of Github.

**Comment by guyonroche** [comment]
:+1: 
Hyperlinks to cells is in my TODO list. I'll close this issue now
