### ISSUE TITLE
add row base on position rows?

### ISSUE THREAD

**Issue by thearabbit** [guyonroche/exceljs#338]
Example: I would like to insert new row after row 5

![image](https://user-images.githubusercontent.com/4495160/27222424-642c4b96-52b6-11e7-8573-23a627211bb2.png)

```js
sheet.addRow({id: 1, name: 'Theara', dob: moment().toDate()}); // set row position
```

**Comment by Rycochet** [comment]
It's in the documentation - `.spliceRows(...)`

**Comment by thearabbit** [comment]
Thanks I will try soon
