### ISSUE TITLE
Support add images

### ISSUE THREAD

**Issue by lgaticaq** [guyonroche/exceljs#34]

**Comment by tnrich** [comment]
I would also like this functionality

**Comment by ryanlin1986** [comment]
It's very important for me too.

**Comment by Laggel** [comment]
I would also like this functionality

**Comment by JoeHitchens** [comment]
I would also like to put images into cells.  Great work on this node module!

**Comment by kachkaev** [comment]
@guyonroche what are your approximate plans on this feature?

Just found this example generated by another library – it might work as a source for inspiration:
http://excelbuilderjs.com/cookbook/insertingPictures.html

![images](https://cloud.githubusercontent.com/assets/608862/18283027/64a378cc-745b-11e6-977a-853ae99cbcc8.png)

**Comment by kachkaev** [comment]
__UPD:__ The above links don’t work any more as the project is no longer maintained. See [stephenliberty/excel-builder.js](https://github.com/stephenliberty/excel-builder.js) for details :–)

**Comment by kachkaev** [comment]
@lgaticaq do you think this can be closed now?

**Comment by lgaticaq** [comment]
yes @kachkaev
