### ISSUE TITLE
Export XLSX on Browser???

### ISSUE THREAD

**Issue by johnrileybjss** [guyonroche/exceljs#342]
Perhaps I'm misunderstanding the function of the library, but I'm trying to export an excel file from the browser using exceljs, and the writefile function doesn't seem to work. When I attempt to invoke writeFile, I get the following error:

`Uncaught TypeError: fs.createWriteStream is not a function`

Is exceljs designed to write files from the browser, or from the server?

My code:

index.html
```
<!DOCTYPE html>
<head>
  <title>Test Excel JS</title>
  <meta charset="utf-8">
  <meta name="description" content="">

  <link rel="stylesheet" href="app.css">
</head>
<body>
  <div>
    <label>Test</label>
    <button onclick="test()">Test this Stuff and Check your console log</button>
  </div>

  <script src="bundle.js"></script>
  <script>
      var test = function(){
          var workbook = generateTestFile();
          workbook.xlsx.writeFile('newtestfile.xlsx')
              .then(function() {
                  console.log('Done Writing file: ');
              });
      };
  </script>
</body>
</html>
```

app.js (bundled to bundle.js using browserify)
```
'use strict';

global.Excel = require('../node_modules/exceljs/dist/es5/exceljs.browser');

global.isRowBold = function(excelRow){
    return excelRow.getCell('name').value === "Jeff";
};

global.getRowColor = function(excelRow){
    return excelRow.getCell('color').value;
};

global.getCellColor = function(excelRow, cell){
    return (excelRow.getCell('name').value === 'John' && cell.value === 0)? 'orange' : excelRow.getCell('color').value;
};

global.getFont = function(isBold, color){
    return {
        name: 'Arial Black',
        color: color,
        family: 2,
        size: 14,
        bold: isBold
    };
};

global.getTestHeader = function(){
    return [
        {key: "id", header: "Id"},
        {key: "name", header: "Name", width: 32},
        {key: "color", header: "Color", width: 10}
    ];
};

global.getTestData = function(){
    return [
        {
            id: 0,
            name: "John",
            color: "green"
        },
        {
            id: 1,
            name: "Rehan",
            color: "blue"
        },
        {
            id: 2,
            name: "Jeff",
            color: "yellow"
        }
    ];
};

global.generateTestFile = function(){
    var workbook = new Excel.Workbook();
    var worksheet = workbook.addWorksheet('Sheet 1');

    //Set Column Headers
    worksheet.columns = getTestHeader();

    //Add Rows
    var testData = getTestData();
    var length = testData.length;
    for(var i = 0; i < length; i++){
        worksheet.addRow(testData[i]);
    }

    //Format Rows
    worksheet.eachRow(function(row, rowNumber){
        var isBold = isRowBold(row);
        row.eachCell(function(cell, colNumber){
            var cellColor = getCellColor(row, cell);
            cell.font = getFont(isBold, cellColor);
        });
    });

    return workbook;
};
```

**Comment by ilya-payrange** [comment]
I don't think the exceljs library is geared to do a download direct to the client. However it can be done with little additional code.

First, exceljs can output a Buffer of file's binary data (instead of writing to the file):
`workbook.xlsx.writeBuffer().then(function(data){ ... /* use data (type of Buffer) here */ } );`
I'm already using it to send file to CDN service.

Second, use something like [FileSaver.js](https://github.com/eligrey/FileSaver.js/) library to create a download function (it is tiny, just wraps different methods for browser compatibility).
I have not used that one yet, but planning to for my project in few weeks.

**Comment by johnrileybjss** [comment]
This did in fact work. Thank you for your help!

**Comment by pleger** [comment]
Hi, 
    I am newbie in this topic, but I want to do the same point using FileSaver.js, but I am very newer. Here, it is my attempt:

 ```
var workbook = generateTestFile();

 var blob = new Blob(workbook, {type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});

saveAs(blob, "publications.xlsx");
```
   
I am absolutely sure that  `new Blob(workbook,...`, but I don't know how to repair that. Can you help me?

Thanks, a newbie

**Comment by SevenZark** [comment]
> @pleger For some reason surrounding `data` in brackets and adding charset to the `type` property did it for me.
> 
> ```
> workbook.xlsx.writeBuffer().then((data) => {
>         const blob = new Blob([data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8' });
>         saveAs(blob, 'tests.xlsx');
>       });
> ```

When I try this, I get 'Failed - No file' in Chrome. Logging blob to the console shows that it's instantiated and looks right as far as I can tell. No idea what to do now.

**Comment by LSL1618** [comment]
```
<script type="text/javascript" src="../static/plugins/file-saver/2.0.5/FileSaver.min.js"></script>
<script type="text/javascript" src="../static/plugins/exceljs/4.4.0/exceljs.min.js"></script>
......
workbook.xlsx.writeBuffer({dateFormat: 'YYYY-MM-DD HH:mm:ss'})
	.then(buffer => {
		let blob = new Blob([buffer], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8'});
		window.saveAs(blob, filename);
	})
	.catch(error => {
		console.error(error);
		throw error;
	});
```
It works for me.
