### ISSUE TITLE
TypeError: Cannot read property 'date1904' of undefined

### ISSUE THREAD

**Issue by huanz** [guyonroche/exceljs#345]
export xlsx by macOS Numbers app, then i use：

```
const workbook = new Excel.Workbook();
workbook.xlsx.readFile('template.xlsx');
```

```
TypeError: Cannot read property 'date1904' of undefined
      at module.exports.reconcile (/Users/bukas/web/api/node_modules/exceljs/dist/es5/xlsx/xlsx.js:108:33)
      at /Users/bukas/web/api/node_modules/exceljs/dist/es5/xlsx/xlsx.js:316:14
      at <anonymous>
```

**Comment by tcstory** [comment]
I also met the same problem

**Comment by Diluka** [comment]
[sample.xlsx](https://github.com/guyonroche/exceljs/files/1140808/sample.xlsx)
here is the sample @guyonroche

**Comment by Diluka** [comment]
this commit https://github.com/guyonroche/exceljs/commit/fba2ea24be9b6aed7affec03e40cc4aa916645e7 fixed this issue
@huanz you should update to latest version and close this issue
