### ISSUE TITLE
How client(express) download excel file?

### ISSUE THREAD

**Issue by sunsnow8** [guyonroche/exceljs#37]
How client(express) download excel file?

**Comment by SwenChan** [comment]
Hope this can help
https://github.com/guyonroche/exceljs/issues/30

**Comment by sivacreatives** [comment]
The above one only works with mongodb. When i do with below code it shows file format is invalid ? why ? and am using only node express

 var workbook = new Excel.Workbook();
    var sheet = workbook.addWorksheet("My Sheet");
    res.setHeader('Content-Type', 'application/vnd.openxmlformats');
    res.setHeader("Content-Disposition", "attachment; filename=" + "Report.xlsx");
    workbook.xlsx.write(res);
    res.end();

**Comment by dgofman** [comment]
Header content type is missing 

![image](https://cloud.githubusercontent.com/assets/147298/12247665/d84a3972-b869-11e5-951f-3e1f9e85e483.png)

**Comment by Techiemouse** [comment]
I am trying to do a similar thing in express using ajax to get the response.
the route:
     workbook.xlsx.write(res)
         .then(function(){
         res.end();
     });

But the ajaxPost call on the client side goes straight into the error, and the response text on the error is utf8 format I believe. Any examples on how to use the module to download the file? Would it be possible to send it as an json object (res.json(data))? Thanks

**Comment by guyonroche** [comment]
I think the Content-Type you are using is not the correct one for xlsx files.
Try: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Comment by Techiemouse** [comment]
Hello and thank for the quick reply,

I have tried that but still no success
This is the server part I have:
```
res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
     res.setHeader("Content-Disposition", "attachment; filename=" + "Report.xlsx");
     workbook.xlsx.write(res)
         .then(function(){
             res.end();
         });
```

This is the ajax part on the client side:
```
success: function(response){
            console.log('success', response);
            var zip = new JSZip(response);
            var file = zip.generate({type: 'blob'});
            saveAs(file, 'table.xlsx');
        },
        error: function(result){
            console.log(result);
        }
```
The result is an object in the error part of the ajax ...
Am I on the wrong path ..should I try a different way? Been trying with a memory buffer too but atm no success. It's a great module and very easy to understand as a stand alone so I must be doing something silly not to be able to implement it.

**Comment by assadtony** [comment]
@Techiemouse any luck? I have stuck with this for days now...

**Comment by guyonroche** [comment]
@Techiemouse - the server side looks good as far as I can see. Not sure why you are unzipping and then zipping the download. What was the error?
When I get some time I'll try to make an example express server

**Comment by Techiemouse** [comment]
This is a weird one for me to be honest as a team mate managed to make it work using a buffer on server side and then receiving it using ajax on client:
```
 var myWritableStreamBuffer = new streamBuffers.WritableStreamBuffer();

        workbook.xlsx.write(myWritableStreamBuffer)
            .then(function(){
                res.json(myWritableStreamBuffer.getContents());
            });

```
`this.ajaxPost({
        async: false,
        url: '/ex',
        data: JSON.stringify(data),
        success: function(response){
            var zip = new JSZip(response);
            var file = zip.generate({type: 'blob'});
            saveAs(file, 'table.xlsx');
        },
        error: this.ajaxErrorCallback.bind(this)
    });`

But it was weird for me that it wasn't working on my computer when running on local host. I was receiving a  Uint8Array error on  the client console and struggled with it for a couple of days until my colleague ran it and worked on his browser. It seems to work fine on the website now as well. So the buffer way should work it might be something with my chrome ..haven't figured that one out as it works for everyone else.

**Comment by assadtony** [comment]
I made it work yesterday. We just has to make sure that the "responseType" on the HTTP Request made by the client was set to "arraybuffer". Then parse that to a Blob file and download it via FileSaver. 
Working as a charm now ;)

**Comment by guyonroche** [comment]
Great to hear! :+1:  I'll close this issue now.
I'll still add an end-to-end test demo to my TODO list though..

**Comment by guyonroche** [comment]
Have added an end-to-end test in the spec folder: [https://github.com/guyonroche/exceljs/tree/master/spec/end-to-end](End to End Specs)

**Comment by rclai** [comment]
Thanks for this, was looking to figure out how to do this. This use case should probably go on the README. And also, your link to the end-to-end test is broken.

**Comment by SaidMarar** [comment]
@assadtony please how do you parse the blob like this ?
```
$.ajax({
            type: "POST",
            url: 'http://localhost:8080/excel',
            dataType: "json",
            success: function( data ){
                        pot=data
bb = new Blob([ab2str(pot.data)], {type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
saveAs(bb,'repo.xlsx');
                    } ,
            error:function(msg){ console.log(msg.responseText);
}
    });
function ab2str(buf) {
    return String.fromCharCode.apply(null, new Uint16Array(buf));
}
```

**Comment by stephengardner** [comment]
This isn't working for me either.  As stated above.  And there isn't really much deciphering from these comments how to do it.  A `res.send` should work...

**Comment by stephengardner** [comment]
Nevermind... For some reason this is only a problem on my local machine...  When I publish live everything works.
Very odd.

**Comment by chenop** [comment]
Can anyone post a client + server working example for downloading a file?
Thanks!

**Comment by molerat619** [comment]
Any news on this?

I want to send an xlsx file back to the client along with some other data all together in a json like this

    {
       excel: BLOB_HERE,
       passengers: [array of passengers...],
       ...
    }

In the frontend I display the passengers and I want to start a download of the excel file at the same time.

**Comment by chenop** [comment]
Here is my example:

**client.js**

$.ajax({
   type: "GET",
   url: "/download",
   xhrFields: { responseType: "blob" },
   data: {},
   success: function(data){
             let blob = new Blob([data], {type: 'vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8'});
            FileSaver.saveAs(blob, 'fileName.xlsx");
   }
})

**node-server.js**

router.get('/download', (req, res) => {
                    let workbook = ExcelManager.createWorkbook();
                    let fileName = ExcelManager.createFilename() + '.xlsx';
                    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
                    res.setHeader('Content-Disposition', 'attachment; filename=' + fileName);
                    return workbook.xlsx.write(res)
                        .then(function() {
                            res.end();
                        });
});

Hope that helps

**Comment by molerat619** [comment]
Great thanks. Looks like I can add any kind of additional data to the res-Object then, I guess?

**Comment by chenop** [comment]
You are sending the file on the res object, so i'm not sure how you an add more data on it.

**Comment by navjotdhanawat** [comment]
Thanks @chenop Its working!!!
```
router.get('/createExcel', function (req, res, next) {
	var workbook = new Excel.Workbook();

	workbook.creator = 'Me';
	workbook.lastModifiedBy = 'Her';
	workbook.created = new Date(1985, 8, 30);
	workbook.modified = new Date();
	workbook.lastPrinted = new Date(2016, 9, 27);
	workbook.properties.date1904 = true;

	workbook.views = [
		{
			x: 0, y: 0, width: 10000, height: 20000,
			firstSheet: 0, activeTab: 1, visibility: 'visible'
		}
	];
	var worksheet = workbook.addWorksheet('My Sheet');
	worksheet.columns = [
		{ header: 'Id', key: 'id', width: 10 },
		{ header: 'Name', key: 'name', width: 32 },
		{ header: 'D.O.B.', key: 'dob', width: 10, outlineLevel: 1, type: 'date', formulae: [new Date(2016, 0, 1)] }
	];

	worksheet.addRow({ id: 1, name: 'John Doe', dob: new Date(1970, 1, 1) });
	worksheet.addRow({ id: 2, name: 'Jane Doe', dob: new Date(1965, 1, 7) });

	res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
	res.setHeader("Content-Disposition", "attachment; filename=" + "Report.xlsx");
	workbook.xlsx.write(res)
		.then(function (data) {
			res.end();
			console.log('File write done........');
		});
});
```

**Comment by muhammadbima20** [comment]
@navjotdhanawat @chenop hi there, can you give me an example of the response from your backend ? in my network tab, i just got `path` response from my backend, and my ajax goes to `error` function,
my response : 

> appName : "/path/to/fileName-2018.xlsx"

thanks

**Comment by navjotdhanawat** [comment]
@muhammadbima20 I think you are using

```
workbook.xlsx.writeFile(filename)
    .then(function() {
        // done
    });
```

Instead of file you have to write steam.

Like this:

```
// write to a stream
workbook.xlsx.write(stream)
    .then(function() {
        // done
    });
```

**Comment by guptroh1978** [comment]
@navjotdhanawat Could you share you client side code as well? Much appreciated

**Comment by guptroh1978** [comment]
> @muhammadbima20 I think you are using
> 
> ```
> workbook.xlsx.writeFile(filename)
>     .then(function() {
>         // done
>     });
> ```
> Instead of file you have to write steam.
> 
> Like this:
> 
> ```
> // write to a stream
> workbook.xlsx.write(stream)
>     .then(function() {
>         // done
>     });
> ```

Could you share you client side code as well? Much appreciated!!

**Comment by guptroh1978** [comment]
> Thanks @chenop Its working!!!
> 
> ```
> router.get('/createExcel', function (req, res, next) {
> 	var workbook = new Excel.Workbook();
> 
> 	workbook.creator = 'Me';
> 	workbook.lastModifiedBy = 'Her';
> 	workbook.created = new Date(1985, 8, 30);
> 	workbook.modified = new Date();
> 	workbook.lastPrinted = new Date(2016, 9, 27);
> 	workbook.properties.date1904 = true;
> 
> 	workbook.views = [
> 		{
> 			x: 0, y: 0, width: 10000, height: 20000,
> 			firstSheet: 0, activeTab: 1, visibility: 'visible'
> 		}
> 	];
> 	var worksheet = workbook.addWorksheet('My Sheet');
> 	worksheet.columns = [
> 		{ header: 'Id', key: 'id', width: 10 },
> 		{ header: 'Name', key: 'name', width: 32 },
> 		{ header: 'D.O.B.', key: 'dob', width: 10, outlineLevel: 1, type: 'date', formulae: [new Date(2016, 0, 1)] }
> 	];
> 
> 	worksheet.addRow({ id: 1, name: 'John Doe', dob: new Date(1970, 1, 1) });
> 	worksheet.addRow({ id: 2, name: 'Jane Doe', dob: new Date(1965, 1, 7) });
> 
> 	res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
> 	res.setHeader("Content-Disposition", "attachment; filename=" + "Report.xlsx");
> 	workbook.xlsx.write(res)
> 		.then(function (data) {
> 			res.end();
> 			console.log('File write done........');
> 		});
> });
> ```

Could you share you client side code as well? Much appreciated!!

**Comment by sujeet27** [comment]
@chenop @navjotdhanawat I'm trying same thing but still stuck. Any help would be much appreciated.

And the file is getting downloaded via postman but not by browser.

Backend Code
            var fileName = 'FileName.xlsx';
            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            res.setHeader('Content-Disposition', 'attachment; filename=' + fileName);
            
            return workbook.xlsx.write(res).then(function(){
               res.end();
            });

Front end code:
$.ajax({
                        url: "/*****/download",
                        type: "GET",
                        data: body,
                        headers: {
                            'Content-type': 'application/json'
                        },
                        responseType: 'blob',
                        success: function (data) {
                            //Data contains the fields that I want to download
                            var saving = document.createElement('a');
                            var csvData;
    //Using a FileSaver or Download library to download the file.
                                saveAs(new Blob([data], { type: "vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8" }), 'test.xlsx');
                            document.body.appendChild(saving);
                            saving.click();
                            document.body.removeChild(saving);
                        },
                        error: function (error) {
                            console.log(error);
                        }
                    });

**Comment by adebright** [comment]
Thanks @chenop and @navjotdhanawat  , I found your solution useful

**Comment by gpbuil** [comment]
Dear All,

I am trying to get the excel file downloaded, but it is not working.
I created a new issue https://github.com/exceljs/exceljs/issues/1541#issue-752460278 
Do you think you can help me out?

Many thanks,

Gines

**Comment by betty-teliapp** [comment]
> Here is my example:
> 
> **client.js**
> 
> ```
> $.ajax({
>    type: "GET",
>    url: "/download",
>    xhrFields: { responseType: "blob" },
>    data: {},
>    success: function(data){
>              let blob = new Blob([data], {type: 'vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8'});
>             FileSaver.saveAs(blob, 'fileName.xlsx");
>    }
> })
> ```
> 
> **node-server.js**
> 
> ```
> router.get('/download', (req, res) => {
>            let workbook = ExcelManager.createWorkbook();
>            let fileName = ExcelManager.createFilename() + '.xlsx';
>            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
>            res.setHeader('Content-Disposition', 'attachment; filename=' + fileName);
>            return workbook.xlsx.write(res)
>                   .then(function() {
>                         res.end();
>                   });
> });
> ```
> 
> Hope that helps

I don't know where you are but I hope you are still doing gods work out ther

**Comment by cantdocpp** [comment]
Nice, thank you for the solution
