### ISSUE TITLE
Cannot call method 'addRow' of undefined

### ISSUE THREAD

**Issue by sunsnow8** [guyonroche/exceljs#38]
#Unhandled rejection TypeError: Cannot call method 'addRow' of undefined 
var workbook = new excelJs.Workbook();
        workbook.xlsx.writeFile("./public/2015-10.xlsx").then(function () {
          var worksheet = workbook.getWorksheet("Sheet 1");
          worksheet.addRow({name: "John Doe", jine: "100", created_at: '2015-09-30'});
          worksheet.commit();
          workbook.commit();
        });

**Comment by jdmcnair** [comment]
I'd imagine once `writeFile` has completed, you'll no longer be able to add a worksheet to the workbook.

**Comment by guyonroche** [comment]
@sunsnow8 @jdmcnair 
The above code uses a document based workbook so you can add things even after you have called writeFile (they won't be in the file of course).
The problem is the workbook has no sheet - you have to add it using the addWorksheet() function.
