### ISSUE TITLE
how to remove borders

### ISSUE THREAD

**Issue by ankit1329** [guyonroche/exceljs#382]
is there some way that i can remove the borders from some cells. there is no border styles such as 'none'.
i want my worksheet to be something like:
![screenshot from 2017-08-27 10-28-34](https://user-images.githubusercontent.com/30821623/29751405-9a153a94-8b12-11e7-9858-bec780c1da0a.png)

**Comment by Wolfchin** [comment]
Hi, did you find a way to achieve this ?

**Comment by pomeo** [comment]
If anybody will search
```
worksheet.views = [{
  showGridLines: false
}];
```
And it's not the same
```
worksheet.properties.showGridLines = false;
```

**Comment by hxmwr** [comment]
> If anybody will search
> 
> ```
> worksheet.views = [{
>   showGridLines: false
> }];
> ```
> 
> And it's not the same
> 
> ```
> worksheet.properties.showGridLines = false;
> ```

There's still outline around the table.

**Comment by pomeo** [comment]
> There's still outline around the table.

This was written in 2018, it's been 5 years already. Read the documentation, most likely everything has already changed

**Comment by hxmwr** [comment]
Maybe there's some difference between numbers and excel

**Comment by vw-vaibhav-badhe** [comment]
but by using this whole sheet border are remove, how to remove particular cell border.
