### ISSUE TITLE
Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by Azimuth67** [guyonroche/exceljs#40]
Hello!

I'm trying to write a number in cell A4 in my excel file and then get the result from cell B4.
Nodejs responds with "Unhandled rejection TypeError: Cannot read property 'target' of undefined".
What am I doing wrong?

var excelfile = "korrtermer/ID101_103_2015.xlsx";
var workbook = new Excel.Workbook();
workbook.xlsx.readFile(excelfile).then(function(){
        var worksheet = workbook.getWorksheet(1);
        console.log(worksheet.getCell("B4").value);
        worksheet.getCell("A4").value = "23,4";
        console.log(worksheet.getCell("B4").value);
        worksheet.commit();
        workbook.commit();
        res.end();
  });

**Comment by shrimpwagon** [comment]
How did you fix this?
