### ISSUE TITLE
Adding formula

### ISSUE THREAD

**Issue by Azimuth67** [guyonroche/exceljs#41]
Hello!

After running the code below and when I open the file the cell shows =A1+B1.
It seems that excel doesn't understand that it is a formula in B1.
What do I do wrong?

```javascript
var Excel = require('exceljs');

exports.test = function(req, res){
  var workbook = new Excel.Workbook();
  var worksheet = workbook.addWorksheet("Sammanstallning");
  workbook.getWorksheet("Sammanstallning");
  worksheet.getCell("B1").value = '=A1+C1';
  worksheet.getCell("C1").value = 0.14;

  workbook.xlsx.writeFile("korrtermer/test_exceljs.xlsx");
  res.end();
}
```

**Comment by guyonroche** [comment]
That's because you have assigned it as a text value. To add a formula, you need to assign it like this:

```javascript
// assuming 0.14 is your calculated result value
worksheet.getCell('B1').value = { formula 'A1+C1', result: 0.14 };  
```

**Comment by ilijaveselica** [comment]
is `result: 0.14` field mandatory?

**Comment by enmanuelr** [comment]
No, it's not mandatory.

**Comment by chirag-compro** [comment]
Can we have a formula parser within, hence the **result** key gets computed automatically for browser version.

**Comment by daniel1433** [comment]
Muchas gracias me ayudo mucho

**Comment by elyohan14** [comment]
> That's because you have assigned it as a text value. To add a formula, you need to assign it like this:
> 
> ```js
> // assuming 0.14 is your calculated result value
> worksheet.getCell('B1').value = { formula 'A1+C1', result: 0.14 };  
> ```

Just a fix, worksheet.getCell('B1').value = { formula: 'A1+C1', result: 0.14 }; instead worksheet.getCell('B1').value = { formula 'A1+C1', result: 0.14 };

**Comment by kiranshankarab** [comment]
Can use the formula by rows and column numbers? 

like this

`worksheet.getCell('B1').value = { formula 'ws.getCell(1, 1)+ws.getCell(1, 3)', result: 0.14 };  `
