### ISSUE TITLE
Deleting the first sheet

### ISSUE THREAD

**Issue by trendsgelo** [guyonroche/exceljs#419]
How can i delete a certain sheet? It's not in the documentation. Thanks

**Comment by mfahmirukman** [comment]
try to console.log the workbook. As I recall, every worksheet created is treated as an element of an array. After accessing that element, you can try nulling it.

**Comment by trendsgelo** [comment]
Thanks , this works for me.

**Comment by getsomecoke** [comment]
The clean way is by using the `removeWorksheet` interface

```js
// Adding worksheet Sheet 1
let worksheet = workbook.addWorksheet('Sheet 1');

// Adding worksheet Sheet 2
let worksheet2 = workbook.addWorksheet('Sheet 2');

// Removing worksheet Sheet 2
workbook.removeWorksheet(worksheet2.id);
```

**Comment by mfahmirukman** [comment]
@getsomecoke thanks, that's actually very helpful
