### ISSUE TITLE
Is there a way to add multiple collumns?

### ISSUE THREAD

**Issue by rcolepeterson** [guyonroche/exceljs#42]
So i can have something like ..

----title---- (100% width)
-----id --- name --- dob ----

----title2----
-----other stuff ----

**Comment by guyonroche** [comment]
I think you are talking about merging cells...

worksheet.getCell('A1').value = 'Title';
worksheet.mergeCells('A1:A3');
worksheet.getCell.('B1').value = 'id';
worksheet.getCell.('B2').value = 'name';
worksheet.getCell.('B3').value = 'dob';
// etc
