### ISSUE TITLE
No way to control summaryBelow or summaryRight

### ISSUE THREAD

**Issue by hpostley** [guyonroche/exceljs#424]
Excel offers the option for outlined rows to collapse either to the top or bottom of the section (summaryBelow) and columns to collapse to either the left or right of the section (summaryRight). Exceljs supports outline but does not provide a way to set the outline direction.

**Comment by amkoehler** [comment]
Hi, did you ever find a solution to this? We ran into the same problem. I have no clue where to start if we wanted to try setting the manually.

**Comment by hpostley** [comment]
We traced the bug into their code but the fix wasn’t totally straightforward and we decided that we didn’t want to maintain it so we switched libraries. 

Howard

**Comment by amkoehler** [comment]
Thanks for the quick response. We may take a crack at this in a fork and will send them a PR if successful. Just curious, what library did you switch to? We started with SheetJS (https://github.com/SheetJS/js-xlsx) but had a bad experience.

**Comment by hpostley** [comment]
We used Excel4node instead for output formatting. I didn’t like sheetjs either.

**Comment by sarahdmsi** [comment]
I took a stab at this in a PR.

**Comment by guyonroche** [comment]
Published in 0.9.0
