### ISSUE TITLE
Is this lib supported now?

### ISSUE THREAD

**Issue by deser** [guyonroche/exceljs#43]
Hi guys! I'm going to use this lib but it seems it isn't supported. Is it stable for production? Thank you

**Comment by guyonroche** [comment]
I did pause active development on this project a while back but I am checking in from time to time.
As for stability, I'm fairly confident it is good (it passes the specs on both Windows and Linux).

**Comment by deser** [comment]
Cool! Thanks a lot!

**Comment by woto** [comment]
We are glad to hear, that you are fine!
Thak you!
