### ISSUE TITLE
worksheet.autoFilter giving an error

### ISSUE THREAD

**Issue by JimGallagherDNB** [guyonroche/exceljs#439]
On trying to add an autofilter to my sheet, an error is thrown.

```
    var outputWorkbook = new Excel.Workbook();
    var worksheet = outputWorkbook.addWorksheet('Direct+ Mapping Tool');
    //add lots of data here
    worksheet.autoFilter(
        {from: {row: 2, column: 1}},
        {to: {row: 2, column: worksheet.columnCount}}
    );
```

Error thrown is:

`TypeError: worksheet.autoFilter is not a function`

I'm using version 0.7.0 of exceljs

Am I doing something wrong?

**Comment by mfahmirukman** [comment]
I think this is how you do it per documentation

```
worksheet.documentation = {
    from: {
        row: 2,
        column: 1
    },
    to: {
        row: 2,
        column: worksheet.columnCount
    }
}
```

I don't think you need the parentheses () for the autofilter

**Comment by JimGallagherDNB** [comment]
Thank you - I should have read the docs more closely! :-(
