### ISSUE TITLE
Losing information when reading from existing file?

### ISSUE THREAD

**Issue by ezintz** [guyonroche/exceljs#44]
Hello,

my goal is to read any kind of Excel file (xlsx, xlsm, xlsb) and modify or add data to it and save it to disk. The file should contain all the changes that the original file that I am reading contains. I was able to figure out how to do that - so far so good. As mentioned in https://github.com/guyonroche/exceljs/issues/35 with the current version 0.2.3 I was not able to produce none corrupt file. So I switched to the older version 0.2.2.

Now I am able to write a file that can be opened with Excel but I lost for example all cell formatting styles e.g. colors. I was also trying a different library with the same result. One option would be to add the styles, if possible, back to the new written file. But a better option would be if I could just use the read file as my "template".

Kind regards,
ezintz

**Comment by richardaum** [comment]
+1

**Comment by Seypopi** [comment]
+1

**Comment by Arlien** [comment]
+1
