### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Aymkdn** [guyonroche/exceljs#440]
Hi,

Thanks for exceljs that is one of the best to deal with Excel, and which has a great documentation 👍 

Could you provide a changelog for [new releases](https://github.com/guyonroche/exceljs/releases) please? Right now there is no information at all, making it difficult to know which changes have been applied to the last releases.

Thank you.

**Comment by Rycochet** [comment]
https://github.com/guyonroche/exceljs/compare/v0.6.2...master

Just change the first part to any tag, you can do the same for the second part like this too -

https://github.com/guyonroche/exceljs/compare/v0.6.2...v0.7.0

**Comment by alonrbar** [comment]
Hi, 

First of all really love your library!

Joining the original commentor, would be nice if there will be a simple changelog (worth a short reading: [https://keepachangelog.com](https://keepachangelog.com)). It doesn't need to start from the beginning of time, just from now on.

Thanks!
