### ISSUE TITLE
commit throws 'undefined is not a function'

### ISSUE THREAD

**Issue by sivacreatives** [guyonroche/exceljs#45]
Below code throws "undefined is not a function'' in workbook.commit() line. 

var workbook = new Excel.Workbook();
    workbook.creator = "Me";
    workbook.lastModifiedBy = "Her";
    workbook.created = new Date(1985, 8, 30);
    workbook.modified = new Date();
    var sheet = workbook.addWorksheet("ssheety");
    var filename = 'test.xlsx';
    var worksheet = workbook.getWorksheet(1);
    worksheet.columns = [
        { header: "Id", key: "id", width: 10 },
        { header: "Name", key: "name", width: 32 },
        { header: "D.O.B.", key: "DOB", width: 10 }
    ];
    worksheet.addRow({id: 1, name: "John Doe", dob: new Date(1970,1,1)});
    worksheet.addRow({id: 2, name: "Jane Doe", dob: new Date(1965,1,7)});
    

    workbook.commit()

    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader("Content-Disposition", "attachment; filename=" + "Report.xlsx");

    workbook.xlsx.write(res);
    res.end();

**Comment by guyonroche** [comment]
You don't need the commit() call. The first line: 
```javascript
var workbook = new Excel.Workbook(); 
```
creates a 'document' workbook. Everything is held in memory until you're done.
The commit() function is only needed for a streaming writer.

**Comment by dgofman** [comment]
I have a same issue

![image](https://cloud.githubusercontent.com/assets/147298/12247621/a6bc14d4-b869-11e5-8b9a-f2fb1f2de24a.png)

**Comment by guyonroche** [comment]
I just noticed the following lines
`workbook.xlsx.write(res);`
`res.end();`

workbook.xlsx.write returns a promise, so the res.end() probably happens before the workbook has had a chance to write anything. Try this:

`workbook.xlsx.write(res)`
`  .then(function() {`
`    res.end();`
`  });`
