### ISSUE TITLE
CSV when last column is blank

### ISSUE THREAD

**Issue by Aymkdn** [guyonroche/exceljs#454]
Hi,

I'm using exceljs to convert some data into a CSV file. Then someone uses this file to import into a database.

However there is a [well known issue with Microsoft Office and CSV](http://nerd.steveferson.com/2012/03/16/excel-export-to-csv-missing-lasttrailing-empty-columns/) : in some cases the delimiter is not correctly added when the last column is empty.

The link provided described it very well.

Any chance to have a fix for this issue ?

Thank you

**Comment by Aymkdn** [comment]
Actually it was an error on my side. Sorry :-)

**Comment by BENLKAMLENourdine** [comment]
@Aymkdn What was the error?

**Comment by Aymkdn** [comment]
I' not sure to remember (3 years ago…), but I think I added a "fake" column at the end of my table to make sure the CSV looks good, then I replaced the last ",fake" of all the rows by empty.
