### ISSUE TITLE
does this support dropdown lists?

### ISSUE THREAD

**Issue by tnrich** [guyonroche/exceljs#47]
For example: 
![image](https://cloud.githubusercontent.com/assets/2730609/11639841/0bc058be-9ce4-11e5-848a-db7002123ee0.png)

Thanks!

**Comment by alangunning** [comment]
@tnrich Did you find an answer for this?

**Comment by ezintz** [comment]
Hello @tnrich and @alangunning, reading dropdown is not possible atm, as well as writing them so far I can see it from the source code. Reading cells that includes a data validation rule returns only a string for ... yeah, I don't know yet.

**Comment by guyonroche** [comment]
Doesn't look too complicated. Will need to study Data Validations (and possible cell names).
Will add it to my TODO list

**Comment by guyonroche** [comment]
Defined Names now added. Data Validations will be the next major feature

**Comment by guyonroche** [comment]
Data Validations (including dropdown lists) now available in 0.2.7

**Comment by tnrich** [comment]
Thanks @guyonroche , great work!

**Comment by SreekanthMekala** [comment]
@guyonroche Can you tell us how to fetch selected value from drop down cell? 

Thanks.
