### ISSUE TITLE
Add multiple rows to Sheet at once

### ISSUE THREAD

**Issue by molerat619** [guyonroche/exceljs#470]
Is it possible to add multiple rows to a sheet at once?

Currently, I prepare an JS array of rows that changes a lot during the loop cycle. Only at the end, I want to add all those rows to the sheet at once, instead of having to loop over them and add them one-by-one.

Something like `sheet.addRows(rows);`.

**Comment by mah110020** [comment]
This should be possible, as per the [documentation](https://github.com/guyonroche/exceljs#rows)

`
let rows = [];
rows.push(["A1", "B1"]);
rows.push(["A2", "B2"]);

worksheet.addRows(rows)
`

**Comment by molerat619** [comment]
Thanks, I found it but forgot to update the issue.
