### ISSUE TITLE
Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.

### ISSUE THREAD

**Issue by chrisfalck** [guyonroche/exceljs#48]
When writing and reading files, the technique used for Promises seems to be deprecated and this might break excel js in future updates.

**Comment by ricmed205** [comment]
+1

**Comment by jdnichollsc** [comment]
+1

**Comment by shallwefootball** [comment]
+1

**Comment by majeeddl** [comment]
+1

**Comment by SwenChan** [comment]
maybe we use anothor promise lib?

**Comment by jdnichollsc** [comment]
use Q promise?

**Comment by guyonroche** [comment]
Thanks for the heads-up. Will look into it

**Comment by healyje** [comment]
Would appreciate it...

**Comment by mvila** [comment]
Promise.defer() is not part of the Promise API anymore:

https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Deferred

Instead of doing:

```javascript
var deferred = Promise.defer();
doSomething(function cb(err, res) {
    if (err) deferred.reject(err); else deferred.resolve(res);
});
return deferred.promise;
```

You should do:

```javascript
return new Promise(function(resolve, reject) {
    doSomething(function cb(err, res) {
        if (err) reject(err); else resolve(res);
    });
});
```

**Comment by floriaanpost** [comment]
Would be great if you could fix this :)

**Comment by guyonroche** [comment]
I'm currently working on adding defined names.
After that I'd like to ES6 it up - and yes, change to a new promise lib!

**Comment by floriaanpost** [comment]
Great!

**Comment by jrsprice** [comment]
+1

**Comment by dzeroone** [comment]
+1

**Comment by guyonroche** [comment]
Merged and Published!
