### ISSUE TITLE
Is there any api provided to export workbook/wooksheet to html format ?

### ISSUE THREAD

**Issue by trendchaser4u** [guyonroche/exceljs#491]

**Comment by mah110020** [comment]
[SheetJS](https://github.com/SheetJS/js-xlsx) has a limited functionality to import/export various formats from/to html. For rendering in applications, I have had good experiences with [handsontable](https://handsontable.com).

**Comment by trendchaser4u** [comment]
@mah110020 great thanks for the notes :) closing this issue.
