### ISSUE TITLE
Ability to use external "moment" package

### ISSUE THREAD

**Issue by nicoladefranceschi** [guyonroche/exceljs#517]
Hi,
I'm using this package in my project and it's great! 
However when I pack my project using **webpack**, I notice that the bundle contains two moment libraries, one that I use in my project, and the other used in this library.
This means that the size on my bundle increases significantly (around 460kb).

In my project I'm using "moment": **"^2.20.1"**
In exceljs it's instead  "moment": **"2.19.3"**

I would suggest to change the dependence's version, but it would be even better to be able to initialized the library passing my own version of moment.

What do you think?

Thanks!

**Comment by guyonroche** [comment]
@nicoladefranceschi I think it would be easier for now to loosen exceljs's dependency requirements (to say >=2.19.3). This will satisfy your need as then npm will align the two without complicating anything.

**Comment by guyonroche** [comment]
Published in v1.0.2
