### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by schroffl** [guyonroche/exceljs#52]
Hi,

I'm currently trying to make my program much more efficient, hence I wanted to use the streaming API.
I've tried following code:
```javascript
const Excel = require('exceljs');
const workbook = new Excel.xlsx.WorkbookWriter({
    'filename': './myfile.xlsx'
});

workbook.getWorksheet(1);
```

The last line returns *undefined*, it's kind of obvious to me since I call this function when the file has not even been read yet. But if I have to wait till it's read, that's no streaming anymore is it? :P  
So what am I missing out, I have no clue how this should work.
Any help is greatly appreciated...

**Comment by schroffl** [comment]
Interesting, I just found [this file](/guyonroche/exceljs/blob/master/lib/stream/xlsx/workbook-reader.js) in your code, it is however missing in node_modules, `npm update` said I have the latest version.
So, you might want to updated your package :D

**Comment by jdnichollsc** [comment]
return undefined +1

**Comment by guyonroche** [comment]
If you change the code to use addWorksheet(sheetname), it should work:

```javascript
var wb = new Excel.stream.xlsx.WorkbookWriter({
  'filename': './myfile.xlsx'
});
var ws = wb.addWorksheet('Foo');
// add rows, data, etc

wb.commit()
  .then(function() {
    // done
  });
```
