### ISSUE TITLE
spliceColumns problem when the number of columns are important

### ISSUE THREAD

**Issue by miniil** [guyonroche/exceljs#520]
Hello,

I have those columns in my files :

RACK | Patch panel | Port | 09/2015 | 10/2015 | 11/2015 | 12/2015 | 01/2016 | 02/2016 | 03/2016 | 04/2016 | 05/2016 | 06/2016 | 07/2016 | 08/2016 | 09/2016 | 10/2016 | 11/2016 | 12/2016 | 01/2017 | 02/2017 | 03/2017 | 04/2017 | 05/2017 | 06/2017 | 07/2017 | 08/2017 | 09/2017 | 10/2017 | 11/2017 | 12/2017 | 01/2018 | 02/2018

I have to delete all the columns before 02/2017

So I do this : sheet.spliceColumns(4, 17);  To delete 17 columns from the 4th one.

But the result is this :

02/2017 | 03/2017 | 04/2017 | 05/2017 | 06/2017 | 07/2017 | 08/2017 | 09/2017 | 10/2017 | 11/2017 | 12/2017 | 01/2018 | 02/2018 | **10/2016 | 11/2016 | 12/2016 | 01/2017**

4 columns are "added", "still" at the end.

But if I do 2 spliceColumns, like this :

sheet.spliceColumns(4, 10);
sheet.spliceColumns(4, 7);

The result is good :

RACK | Patch panel | Port | 02/2017 | 03/2017 | 04/2017 | 05/2017 | 06/2017 | 07/2017 | 08/2017 | 09/2017 | 10/2017 | 11/2017 | 12/2017 | 01/2018 | 02/2018

Thanks for your help.

**Comment by guyonroche** [comment]
Fixed in v1.0.1
