### ISSUE TITLE
adding Image doesn't work  

### ISSUE THREAD

**Issue by labs00** [guyonroche/exceljs#521]
My files:
![image](https://user-images.githubusercontent.com/11719153/37556343-9a1137f2-2a2f-11e8-8c1f-55c6d4868b0e.png)

My excel file:
![image](https://user-images.githubusercontent.com/11719153/37556375-00a3bcba-2a30-11e8-9dce-f3c38303621c.png)

My code

```
const excel = require('exceljs');
const fs = require('fs');
(async () => {
    try {
        const wb = new excel.Workbook();
        const file = await wb.xlsx.readFile('excel1.xlsx');
        const ws = file.getWorksheet('lal'); // sheetname is 'lal'
        
        const imgId = wb.addImage({
            buffer: fs.readFileSync('dk2.png'),
            extension: 'png'
        });

        // not work
        ws.addBackgroundImage(imgId);
        // not work
        ws.addImage(imgId, 'I1:I2');
        // not work
        ws.addImage(imgId, {
            tl: { col: 8, row: 2 },
            br: { col: 8, row: 2 }
        });
        console.log('file img', imgId); // id=0

    } catch (error) {
        console.log('error', error);
    }
})();

```

after running the code , the excel1.xlsx changed nothing,  there wasn't an image in it. and the code didn't throw any error or warning, could anyone help me? @guyonroche

**Comment by Gluhovroma** [comment]
I choose the library for Excel. Who can confirm this problem?

**Comment by Gluhovroma** [comment]
same here.

**Comment by guyonroche** [comment]
@labs00  I see that you are reading the excel1.xlsx file at the start, but not 'saving' it after adding the image. Until you save (using writeFile) the changes will only be in memory

**Comment by Gluhovroma** [comment]
wow

**Comment by Gluhovroma** [comment]
wow. thank you for answer!!

**Comment by wangyiman** [comment]
> @labs00 I see that you are reading the excel1.xlsx file at the start, but not 'saving' it after adding the image. Until you save (using writeFile) the changes will only be in memory

How to save ?

**Comment by padampadampadam** [comment]
can we have complete code along with writeFile()? I am looking for to save the image in excel using javascript.

**Comment by Gluhovroma** [comment]
> can we have complete code along with writeFile()? I am looking for to save the image in excel using javascript.

Hello,
Nodejs example:
async getReport(data, type, translations) {
        let buffer;
        switch(type) {
            case "pdf":
            buffer = await this.pdfBuilder.getPdfBuffer(data, translations);
            break;
            case "xls":
            buffer = await this.excelBuilder.getExelBuffer(data, translations);
            break;
        }
        return buffer
    }
    writeFile(buffer:any, format:string) {       
        return new Promise((resolve, reject) => {            
            let buf = Buffer.from(buffer);
            let title = this.createHash() + '.' +  format;
            fs.writeFile(__dirname +'/output/' + title, buf, function(err) {
                if (err) {
                    return  reject(err);
                }
                return resolve(title);
              });
        });
    }
    createHash() {
        return  crypto.randomBytes(20).toString('hex');
    }

public async getExelBuffer(report: any, translations:any): Promise<any> {         
        let workbook: Workbook = await this.createWorkBook(report, translations);
        return await workbook.xlsx.writeBuffer()

    }


browser example:

getExelBuffer() 
and then

    createBlob(data: any, name:string, type:string, mimeType:string) {
        let blob = new Blob([data], { type : mimeType });
        let a = document.createElement("a");
        document.body.appendChild(a);
        let url = window.URL.createObjectURL(blob);
        a.href = url;
        a.download = this.createPath(name, type);
        a.click();
        window.URL.revokeObjectURL(url);
    }

look at this repo 
https://github.com/Gluhovroma/report-export
