### ISSUE TITLE
ReferenceError: err is not defined

### ISSUE THREAD

**Issue by ktrzeciaknubisa** [guyonroche/exceljs#53]
When running exceljs under JXcore package, I've encountered an error:

```bash
[...]/node_modules/exceljs/lib/utils/utils.js:38
                    deferred.reject(err);
                                    ^
ReferenceError: err is not defined
    at [...]/node_modules/exceljs/lib/utils/utils.js:38:37
```

It looks like there is a typo in that line and should be `deferred.reject(error)` instead of `deferred.reject(err)`.

**Comment by guyonroche** [comment]
Yes - my bad. Should be fixed now in v0.2.5
