### ISSUE TITLE
how to save open xlsx?

### ISSUE THREAD

**Issue by RephoneYin** [guyonroche/exceljs#531]
I opened an xlsx file, updated one cell and I want to save the xlsx. How to do that?
My code as below:
`
    let workbook = new Excel.Workbook();

    workbook.xlsx.readFile(__dirname + '\\utils\\mto.xlsx').then(worksheet => {

        let basicSheet = workbook.getWorksheet('sheet1');
        
        basicSheet.getCell('D10').value = 30;
        
        workbook.writeFile(__dirname + '\\utils\\mto.xlsx').then(() => {
            console.log('write done!')
        });

    });

`

Run the code above, I got this error: 

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): RangeError: Invalid time value

**Comment by guyonroche** [comment]
@RephoneYin out of interest - can you tell me what value was originally in cell D10?
My suspicion is that it is a date - with a numFmt implying a date and that might be affecting things.
Also - to avoid the UnhandledPromiseRejection (and get more info about your error), you should add .catch handler(s)...

```
let workbook = new Excel.Workbook();
workbook.xlsx.readFile(__dirname + '\\utils\\mto.xlsx')
  .then(() => {
    let basicSheet = workbook.getWorksheet('sheet1'); 
    basicSheet.getCell('D10').value = 30; 

    return workbook.writeFile(__dirname + '\\utils\\mto.xlsx')
  })
  .then(() => {
    console.log('write done!')
  })
  .catch(error => {
    console.error(error.stack);
  });


```

**Comment by RephoneYin** [comment]
@guyonroche Thanks a lot. Problem has been done using other tech.

**Comment by kauly** [comment]
@RephoneYin  Can you share this tech please? I

**Comment by Seypopi** [comment]
@kauly python can be a good choice
