### ISSUE TITLE
Is it possible to read without excel program?

### ISSUE THREAD

**Issue by Jongkeun** [guyonroche/exceljs#540]
I'm developing some program that handles Excel.
Some users have no Excel program.
So I am checking libraries if that is possible.
Is this library possible?

**Comment by zgriesinger** [comment]
To try to answer the question in the title, yes the library can read in and process Excel files without the program installed. However, the library only handles the manipulation of Excel files, if the end users wish to view them they will have to have a program to open the `.XLS*` file or you will have to export as something else.

**Comment by Jongkeun** [comment]
Thanks, @zgriesinger .
I wanna just read the Excel.
My question was answered.
