### ISSUE TITLE
Issue with Webpack build targeting browser

### ISSUE THREAD

**Issue by Peter-Van-Drunen** [guyonroche/exceljs#606]
Obviously, this project is largely focused on server-side processing of workbooks for node environments, but I need some of the functionality for usage in the browser a la [this section of the README](https://github.com/guyonroche/exceljs#browser). However when I import the exceljs.browser file via `import ExcelJS from 'exceljs/dist/es5/exceljs.browser'` and build with webpack I still get errors telling me I'm missing the 'fs' module. Is this project compatiable with a browser environment using my toolchain?

Here's my little function:

```
const Excel = require('exceljs/dist/es5/exceljs.browser');

const excelExport = (data) => {
    // Do something...
}

export default excelExport;

```
And here's one of many identical webpack errors I get for various modules after importing the package:
```
ERROR in ./node_modules/exceljs/dist/es5/csv/csv.js
Module not found: Error: Can't resolve 'fs' in 'file/lo/cation/exceljs/dist/es5/csv'
```

Could this be related to my usage of webpack? Maybe incorrect configuration? I've been unable to find any documentation on this issue elsewhere so that might be the cause.

**Comment by nevace** [comment]
Add this to your webpack config:

```
node: { fs: 'empty' }
```

**Comment by Peter-Van-Drunen** [comment]
The solution @nevace provided fixed the webpack build.

It's worth noting for anyone else that had this issue that once you make the above change the easiest way to write the file to a download is to use workbook.xlsx.writeBuffer to get a base64 string of the file and go from there.
