### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by lirantal** [guyonroche/exceljs#608]
Hi,

I'm a member of the Node.js Security WG and we received a report regarding a security issue with this module. We tried inviting the author by e-mail but received no response so I'm opening this issue and inviting anyone with commit and npm publish rights to collaborate with us on a fix.

**Comment by Steague** [comment]
@lirantal Can you elaborate on the issue a bit? We use this package pretty extensively and need to know if it's something we need to address.

**Comment by dboune** [comment]
@Steague Looks like they will wait 45 days to disclose, so something around 33 days left.

**Comment by lirantal** [comment]
The point is that we don't want to disclose the vulnerability in the open to not let other take advantage of this knowledge and harm users.

Can you give me an e-mail address to invite to HackerOne platform one of the maintainers with commit and publish access of this npm module to further discuss this vulnerability and allow for a fix to be shipped?

**Comment by lirantal** [comment]
pinging @guyonroche before we go ahead with the disclosure

**Comment by guyonroche** [comment]
Have discussed the issue and will publish a fix shortly

**Comment by guyonroche** [comment]
Addressed in v1.6.0

**Comment by ZJONSSON** [comment]
@lirantal please see discussion on https://github.com/guyonroche/exceljs/commit/9066cd89a9fad055166b53ce9e75a42e7636bac1#comments 

Also please fwd to the Node.js Security WG (@nodejs)

I really appreciate all the work, but we also need to be able to trust in the validation process of what constitutes a CVE - otherwise alerts could be ultimately ignored

**Comment by lirantal** [comment]
Hi @ZJONSSON,

Appreciate the feedback and I agree that this is debatable. Actually what we've done in the past in cases like this where this is borderline and probably not in the scope of the library is that we ask the maintainer to add a security disclaimer in the README to clarify possible attack vectors and resolve the issue without assigning a CVE. In this report I may have jumped too quickly at it but seeing that this was a popular library and potentially impacting many users if they do follow the paste-to-html practice then it seemed to make sense to report it as such.

Indeed Guy didn't fix anything specifically but added another method to hint users of the potential security issue to support my above declared intentions.

Your input is very much valid and to the point, and I'll take it into account for future cases.
I'm happy to help or discuss further for anything we can improve.

**Comment by guyonroche** [comment]
I agree with all the above comments. My rationale with adding the html property was 1) it has no impact on any other part of exceljs and therefore no impact on any dependent libs or apps and 2) provides a simple convenience that outputs html safe strings for rendering.
Of course the ultimate responsibility in rendering safe html pages is with the app but from my own experience, it's nice when a lib makes things like this easy - especially as it implies someone has already thought the issue through and provided a transform that works.
