### ISSUE TITLE
How import exceljs

### ISSUE THREAD

**Issue by diegohdez90** [guyonroche/exceljs#610]
I was trying to import `exceljs ` through `import`
I read README.md, it says in 

https://github.com/guyonroche/exceljs#interface are using `require`, and I need how use it via `import`?

Any idea how use `exceljs` with `import`?

**Comment by diegohdez90** [comment]
Without problem @nevace 
Thanks.

Keep coding.

**Comment by ludgerey** [comment]
This is apparently outdated. This worked for me:

```
import * as ExcelJS from "exceljs";
```

**Comment by tomchiverton** [comment]
That fails :
```
import * as ExcelJS from "exceljs";

const workbook = new ExcelJS.Workbook();
```

```
const workbook = new ExcelJS.Workbook();
                 ^

TypeError: ExcelJS.Workbook is not a constructor
```

Works
```
import ExcelJS from 'exceljs';

const workbook = new ExcelJS.Workbook();
```
