### ISSUE TITLE
fs.createWriteStream is not a function 

### ISSUE THREAD

**Issue by diegohdez90** [guyonroche/exceljs#611]
I was coding in this week with `exceljs`

I have a lot of problems to export an use this great dependency.

In my project I have a json object with values and I want to export this data in excel xlsx file

```
import ExcelJS from 'exceljs/dist/es5/exceljs.browser';
...
exportToExcel(data, headers) {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('DYC-Survey');
    const columns = headers.map((header) => ({
      header, id: header, width: (header.length > 15) ? header.length + 8 : 20,
    }));
    worksheet.columns = columns;
    worksheet.addRows(data);
    const header = worksheet.getRow(0);
    header.font = { bold: true, size: 18 };
    worksheet.pageSetup.horizontalCentered = true;
    worksheet.pageSetup.verticalCentered = true;
    workbook.xlsx.writeFile(`${Date.now()}_feedbacks.xlsx`)
    .then(() => {
      console.log('File created');
    }).catch(() => {
      console.log('Error in export file');
    });
}
```
In my console display this message:

`fs.createWriteStream is not a function` 

The error launches in the line where says `workbook.xlsx.writeFile()` where I call `writeFile()` method

Somebody have any idea what happen in my code?

Also I added this line in my `webpack.config`:

`node : { fs: 'empty' }`

Thanks.

**Comment by dboune** [comment]
The method `writeFile` doesn't appear to currently support the browser. It certainly would be nice if it did.

Instead, you can use `writeBuffer`, store it as a blob, and then use some method to cause the blob to be downloaded.

For example -- I'm using the FileSaver module here:
```js
workbook.xlsx.writeBuffer()
  .then(buffer => FileSaver.saveAs(new Blob([buffer]), `${Date.now()}_feedback.xlsx`))
  .catch(err => console.log('Error writing excel export', err)
```

**Comment by dboune** [comment]
@diegohdez90: Very welcome! Glad I could help! When you are ready you might close this issue unless you want to turn it into a feature request. I’d do it for you, but I’m not a maintainer here.. just a wanderer who hoped to help.

**Comment by diegohdez90** [comment]
Thanks @dboune, it works.
Keep coding
Good luck.

**Comment by parasharrajat** [comment]
It's Closed but. Can somebody help with above error on electron? I am using angular to build the UI on Electron app but in the component file Which has access to node apis including File system. I am getting this error but other node ibraries are working fine.

**Comment by tusharp1206** [comment]
> @diegohdez90: Very welcome! Glad I could help! When you are ready you might close this issue unless you want to turn it into a feature request. I’d do it for you, but I’m not a maintainer here.. just a wanderer who hoped to help.

Heyy!, but what if i dont want to download the file and just want to  save it to  a folder on a remote server so how is it possible like i am using nodes writeFile to do this, where i am injecting the required parameters i.e the path and the file content and here in my case  the file content would be coming from the database so am pretty confused as i am getting errors.



would appreciate your help! thank you.
