### ISSUE TITLE
If I add more then 1 sheet all sheets are hidden except for the 1st sheet

### ISSUE THREAD

**Issue by techiekayen** [guyonroche/exceljs#617]
Hi, I am nor sure if this is a bug or if some new functionality has been added but I am using the latest version of exceljs (1.5.1) and if I add more then one sheet to a workbook then all sheets after the first sheet are hidden and I am not able to make them visible using code.

Here is some sample code to re-produce the issue:

```
const Exceljs = require("exceljs");

let wb = new Exceljs.Workbook();

let sheet1 = wb.addWorksheet("s1");
let sheet2 = wb.addWorksheet("s2");

wb.xlsx.writeFile("myWb.xlsx");

```

If you open this workbook sheet "s2" is hidden. I tried using: 

`sheet2.state = "show";
`
but this doesn't help. Is this a bug or am I missing something?

This works if I use 1.4.6.

Thanks!

**Comment by mp-ffx** [comment]
hi, just set the state to 'visible' and it should work! see #621 for details

**Comment by techiekayen** [comment]
You are a steely eyed missile man! Thanks, that woks a treat and solves my problem.

The README should be updated to let others know about this and maybe the default should be "visible" when creating adding a new worksheet?
