### ISSUE TITLE
exceljs fails in aws lambda Cannot find module '../../xlsx/.rels' 

### ISSUE THREAD

**Issue by jpizarrom** [guyonroche/exceljs#70]
**solutiion** 
`mv ./lib/xlsx/.rels ./lib/xlsx/workbook.xml.rels`

**log**
`
Unhandled rejection Error: Cannot find module '../../xlsx/.rels' at Function.Module._resolveFilename (module.js:338:15) at Function.require.resolve (module.js:384:19) at Object.WorkbookWriter.addOfficeRels (/var/task/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:191:44) at Object.module.exports (/var/task/node_modules/exceljs/lib/stream/xlsx/workbook-writer.js:71:14) at /var/task/index.js:51:24 at Promise._execute (/var/task/node_modules/bluebird/js/release/debuggability.js:272:9) at Promise._resolveFromExecutor (/var/task/node_modules/bluebird/js/release/promise.js:468:18) at new Promise (/var/task/node_modules/bluebird/js/release/promise.js:77:14) at json_spec_to_xls (/var/task/index.js:37:12) at Transform.<anonymous> (/var/task/index.js:124:17) at Transform.emit (events.js:95:17) at Transform.<anonymous> (_stream_readable.js:765:14) at Transform.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:427:10) at emitReadable (_stream_readable.js:423:5) at readableAddChunk (_stream_readable.js:166:9)
`

**Comment by guyonroche** [comment]
The whole code-base has been refactored since this was reported. I'm going to assume it is closed. If not, please re-open. Thanks
